Repository Stratio/egeo, pull requests merged in 2018-10, with the labels that each got.

#669 [NA] fix(web): Fix web generator task and add some minor style changes
  angular.json
  src/demo-app/app/modules/general/changelog/changelog.scss
  src/demo-app/app/modules/general/getting-started/getting-started.scss
  src/demo-app/app/modules/theme/grid/grid.scss
  src/demo-app/app/shared/menu/menu.scss
Labels: demo

#670 [SAAS-604] feat(st-form): Add ID parameter to the component
  src/lib/st-form/st-form.component.html
Labels: feature

#671 [NA] fix(st-select): When select is in a form, user has to click two times in an option to select it
  CHANGELOG.md
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.spec.ts
  src/lib/st-select/st-select.ts
Labels: bug

#673 [NA] fix(st-tag-input): Remove array value as string from view
  CHANGELOG.md
  src/lib/st-tag-input/st-tag-input.component.html
Labels: bug

#674 Cherry pick: [NA] fix(st-tag-input): Remove array value as string from view
  CHANGELOG.md
  src/lib/st-tag-input/st-tag-input.component.html
Labels: cherry-pick

#675 [secty-643] fix bad behavior if user is searching something and click checkbox all (it must be select only filtered list)
  CHANGELOG.md
  src/lib/st-two-list-selection/list-selection/list-selection.component.spec.ts
  src/lib/st-two-list-selection/list-selection/list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.spec.ts
  src/lib/st-two-list-selection/st-two-list-selection.ts
Labels: bug

#677 Cherry-pick: [NA fix (st-select): When select is in a form, user stil l has to click two times to select an option
  CHANGELOG.md
  src/lib/st-form/st-form-field/st-form-field.component.html
  src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  src/lib/st-form/st-form-field/st-form-field.component.ts
  src/lib/st-select/st-select.ts
Labels: bug, cherry-pick

#676 [NA fix (st-select): When select is in a form, user still has to click two times to select an option
  CHANGELOG.md
  src/lib/st-form/st-form-field/st-form-field.component.html
  src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  src/lib/st-form/st-form-field/st-form-field.component.ts
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.ts
Labels: bug

#678 [NA] feat(st-horizontal-tabs): Apply new design according to UX specifications
  CHANGELOG.md
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.html
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.scss
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.html
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.scss
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.spec.ts
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.ts
  src/theme/components/_horizontal-tabs.scss
Labels: style

#679 Cherrypick [SECTY-643] (st-two-list): bad behavior
  CHANGELOG.md
  src/lib/st-two-list-selection/list-selection/list-selection.component.spec.ts
  src/lib/st-two-list-selection/list-selection/list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.spec.ts
  src/lib/st-two-list-selection/st-two-list-selection.ts
Labels: bug, cherry-pick

#680 [NA] feat(st-modal): Allow to add a cross button to close modal
  CHANGELOG.md
  src/egeo-demo/st-modal-demo/st-modal-demo.component.ts
  src/lib/st-modal/st-modal.component.html
  src/lib/st-modal/st-modal.component.spec.ts
  src/lib/st-modal/st-modal.component.ts
  src/lib/st-modal/st-modal.model.ts
  src/theme/components/_modal.scss
Labels: feature

#681 [NA fix (st-select): Close select when user clicks outside
  CHANGELOG.md
  src/lib/directives/st-click-outside/st-click-outside.component.spec.ts
  src/lib/directives/st-click-outside/st-click-outside.directive.ts
  src/lib/public_api.ts
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.module.ts
  src/lib/st-select/st-select.spec.ts
  src/lib/st-select/st-select.ts
Labels: bug

#682 Cherry-pick: [NA] fix (st-select): Close select when user clicks outside
  CHANGELOG.md
  src/lib/directives/st-click-outside/st-click-outside.component.spec.ts
  src/lib/directives/st-click-outside/st-click-outside.directive.ts
  src/lib/public_api.ts
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.module.ts
  src/lib/st-select/st-select.spec.ts
  src/lib/st-select/st-select.ts
Labels: bug

#683 [NA] fix(st-file-button): add id to input
  CHANGELOG.md
  src/lib/st-file-button/README.md
  src/lib/st-file-button/st-file-button.component.html
  src/lib/st-file-button/st-file-button.component.ts
Labels: bug
