Repository Stratio/egeo, pull requests merged in 2018-09, with the labels that each got.

#649 [NA] feat(st-dropdown-menu): Put pointer cursor to items
  CHANGELOG.md
  src/theme/components/_dropdown-menu.scss
Labels: style

#650 [NA] feat(st-input): Label is only generated if it is not empty
  CHANGELOG.md
  src/lib/st-input/st-input.component.html
  src/lib/st-input/st-input.component.spec.ts
Labels: enhancement

#651 [SAAS-495] fix(st-bubble): Fix visible style
  CHANGELOG.md
  src/theme/components/_bubble.scss
Labels: bug, style

#652 [NA] fix(st-dropdown-menu): Fix wrong visualization on small screens
  CHANGELOG.md
  src/theme/components/_dropdown-menu.scss
Labels: bug, style

#648 [SECTY-563] feat(st-two-list): not show check all if list is empty. Apply new styles.
  CHANGELOG.md
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.html
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.ts
  src/lib/st-two-list-selection/list-item/list-item.component.html
  src/lib/st-two-list-selection/list-item/list-item.component.scss
  src/lib/st-two-list-selection/list-item/list-item.component.ts
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
  src/lib/st-two-list-selection/list-selection/list-selection.component.html
  src/lib/st-two-list-selection/list-selection/list-selection.component.scss
  src/lib/st-two-list-selection/list-selection/list-selection.component.spec.ts
  src/lib/st-two-list-selection/list-selection/list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.model.ts
  src/lib/st-two-list-selection/st-two-list-selection.view.component.html
  src/lib/st-two-list-selection/st-two-list-selection.view.component.scss
  src/lib/st-two-list-selection/st-two-list-selection.view.component.spec.ts
  src/lib/st-two-list-selection/st-two-list-selection.view.component.ts
Labels: enhancement, style

#653 [NA] style(st-dropdown-menu): Improve item design
  CHANGELOG.md
  src/theme/components/_dropdown-menu.scss
Labels: style

#654 [NA] style(st-button, st-input, st-spinner): Apply minor style changes
  CHANGELOG.md
  src/theme/components/_button.scss
  src/theme/components/_input.scss
  src/theme/components/_spinner.scss
  src/theme/utils/_fonts.scss
  src/theme/utils/_forms.scss
Labels: style

#619 [NA]chore(Global)Update to Angular 6
  .angular-cli.json
  CHANGELOG.md
  angular.json
  package.json
  src/demo-app/app/app.service.ts
  src/demo-app/app/modules/general/changelog/changelog.service.ts
  src/demo-app/app/modules/general/changelog/changelog.ts
  src/demo-app/app/modules/theme/colors/color/color.ts
  src/demo-app/app/modules/theme/colors/colors.service.ts
  src/demo-app/app/modules/theme/colors/colors.ts
  src/demo-app/app/modules/theme/fonts/fonts.ts
  src/demo-app/app/modules/theme/icons-demo/icons-demo.service.ts
  src/demo-app/app/modules/theme/icons-demo/icons-demo.ts
  src/demo-app/demo-app-module.ts
  src/demo-app/polyfills.ts
  src/egeo-demo/shared/st-demo-logger/st-demo-logger.service.ts
  src/egeo-demo/shared/st-demo-logger/st-demo-logger.ts
  src/egeo-demo/st-tree-demo/st-tree-demo.ts
  src/lib/st-alerts/st-alerts.component.spec.ts
  src/lib/st-alerts/st-alerts.model.spec.ts
  src/lib/st-alerts/st-alerts.model.ts
  src/lib/st-alerts/st-alerts.service.spec.ts
  src/lib/st-alerts/st-alerts.service.ts
  src/lib/st-breadcrumbs/st-breadcrumbs-item/st-breadcrumbs-item.component.spec.ts
  src/lib/st-header/menu-option/menu-option.ts
  src/lib/st-input/st-input.component.ts
  src/lib/st-modal/st-modal.service.spec.ts
  src/lib/st-modal/st-modal.service.ts
  src/lib/st-search/st-search.component.ts
  src/lib/st-select/st-check-validations.ts
  src/lib/st-textarea/st-textarea.component.ts
  src/lib/tests/router-stub.ts
  src/lib/utils/egeo-resolver/egeo-resolve-model.ts
  src/lib/utils/egeo-resolver/egeo-resolve.service.spec.ts
  src/lib/utils/egeo-resolver/egeo-resolve.service.ts
  tools/gulp/tasks/generate-theme.ts
  tools/gulp/tasks/others.ts
  tools/gulp/tasks/payload.ts
  tools/gulp/tasks/validate-release.ts
  tools/gulp/util/rename-scss.ts
  tools/package-tools/generate-docs.ts
  tools/package-tools/gulp/build-scss-task.ts
  tools/package-tools/inline-resources.ts
  tools/package-tools/metadata-inlining.ts
  tools/package-tools/metadata-reexport.ts
  tools/package-tools/pure-annotations.ts
  tools/package-tools/rollup-helpers.ts
  tools/package-tools/typescript-transpile.ts
Labels: blocked, build

#657 [SAAS-555] feat(st-button): add small toolbar button
  CHANGELOG.md
  src/egeo-demo/st-button-demo/st-button-demo.component.html
  src/theme/components/_button.scss
Labels: style

#658 [NA] feat(st-two-list): adds new styles
  CHANGELOG.md
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
  src/lib/st-two-list-selection/list-selection/list-selection.component.scss
Labels: style

#659 [NA] feat(st-tag-input): Allow user to generate arrays of integers and numbers
  CHANGELOG.md
  src/demo-app/app/modules/general/about/about.scss
  src/demo-app/styles.scss
  src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.html
  src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.ts
  src/lib/st-tag-input/README.md
  src/lib/st-tag-input/st-tag-input.component.html
  src/lib/st-tag-input/st-tag-input.component.spec.ts
  src/lib/st-tag-input/st-tag-input.component.ts
Labels: feature

#662 [NA] feat(st select): can search options
  CHANGELOG.md
  src/egeo-demo/st-select-demo/select-demo.html
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.spec.ts
  src/lib/st-select/st-select.ts
Labels: enhancement

#663 [NA] enhanement(st-dropdown-menu): Fix demo and next release version
  CHANGELOG.md
  pom.xml
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.component.scss
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.html
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
Labels: demo

#667 [NA] fix(st-two-list): bad behavior with virtual scroll and checkbox all
  CHANGELOG.md
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
  src/lib/st-two-list-selection/list-selection/list-selection.component.html
  src/lib/st-two-list-selection/list-selection/list-selection.component.scss
Labels: bug

#668 [NA] fix(st-two-list): bad behavior with virtual scroll and checkbox all
  CHANGELOG.md
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
  src/lib/st-two-list-selection/list-selection/list-selection.component.html
  src/lib/st-two-list-selection/list-selection/list-selection.component.scss
Labels: cherry-pick
