Repository Stratio/egeo, pull requests merged in 2018-05, with the labels that each got.

#606 [NA]chore(maven): Update stratio parent artifact to 0.10.0
  CHANGELOG.md
  pom.xml
Labels: build

#605 [NA]fix(st-horizontal-tabs): fix activeOption on init the component
  CHANGELOG.md
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.html
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.ts
  src/lib/st-horizontal-tabs/README.md
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.html
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.spec.ts
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.ts
Labels: blocked

#607 [NA]fix(st-form-list): Select dropdown is not displayed
  CHANGELOG.md
  src/egeo-demo/st-form-list-demo/st-form-list-demo.ts
  src/lib/st-form-list/st-form-list.scss
Labels: bug

#609 [NA]fix(st-sidebar): Avoid to create a list of children for a section when its item list is empty
  src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.html
  src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.ts
Labels: bug

#610 [NA]perf(st-sidebar): Change active input from string to a StSidebarItem
  CHANGELOG.md
  src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.ts
  src/lib/st-sidebar/README.md
  src/lib/st-sidebar/st-sidebar-item-list/README.md
  src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.html
  src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.spec.ts
  src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.ts
  src/lib/st-sidebar/st-sidebar.component.spec.ts
  src/lib/st-sidebar/st-sidebar.component.ts
Labels: enhancement

#611 [NA]feat(st-table): Add input for adding classes from the egeo theme to table
  CHANGELOG.md
  src/egeo-demo/st-table-demo/st-table-demo.component.html
  src/lib/st-table/README.md
  src/lib/st-table/st-table.component.html
  src/lib/st-table/st-table.component.spec.ts
  src/lib/st-table/st-table.component.ts
  src/theme/components/_table.scss
Labels: feature

#614 [NA]fix(sidebar): Fix item displaying when label is too long
  src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.ts
  src/theme/components/_sidebar.scss
Labels: bug
