Repository Stratio/egeo, pull requests merged in 2018-12, with the labels that each got.

#694 [EGE-446] fix(st-select): Disable native autocomplete
  CHANGELOG.md
  src/lib/st-select/st-select.html
Labels: bug

#696 [EGE-442] fix(st-breadcrumbs): Allow to configure visualization mode as "default" or "title"
  CHANGELOG.md
  src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.html
  src/lib/st-breadcrumbs/README.md
  src/lib/st-breadcrumbs/st-breadcrumbs-item/st-breadcrumbs-item.component.html
  src/lib/st-breadcrumbs/st-breadcrumbs.component.html
  src/lib/st-breadcrumbs/st-breadcrumbs.component.spec.ts
  src/lib/st-breadcrumbs/st-breadcrumbs.component.ts
  src/lib/st-breadcrumbs/st-breadcrumbs.interface.ts
  src/theme/components/_breadcrumbs.scss
Labels: feature

#697 [EGE-448] fix(st-fullscreen): Allow to customize title
  CHANGELOG.md
  src/egeo-demo/st-fullscreen-layout-demo/st-fullscreen-layout-demo.html
  src/egeo-demo/st-fullscreen-layout-demo/st-fullscreen-layout-demo.scss
  src/lib/st-fullscreen-layout/README.md
  src/lib/st-fullscreen-layout/st-fullscreen-layout.html
  src/lib/st-fullscreen-layout/st-fullscreen-layout.spec.ts
  src/lib/st-fullscreen-layout/st-fullscreen-layout.ts
  src/theme/components/_fullscreen-layout.scss
Labels: breaking-change, feature

#698 [NA] fix(breadcrumbs): Publish StBreadCrumbMode to can be referenced from outside
  src/lib/public_api.ts
Labels: bug

#700 [NA] feat(st-foreground-notifications): must admit an empty list
  CHANGELOG.md
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.html
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.html
  src/lib/st-foreground-notifications/st-foreground-notifications.ts
Labels: enhancement

#702 [NA] fix(st-foreground-notifications): doesnt change visible var value inside component
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.html
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.spec.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.ts
Labels: bug
