Repository Stratio/egeo, pull requests merged in 2018-04, with the labels that each got.

#580 feat(st-form)[UX-72]: Allow to display related fields in the same row
  CHANGELOG.md
  src/egeo-demo/st-form-demo/json-schema.ts
  src/egeo-demo/st-form-demo/st-form-demo.html
  src/lib/st-form/spec/resources/json-schema.ts
  src/lib/st-form/spec/st-form.component.spec.ts
  src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  src/lib/st-form/st-form.component.html
  src/lib/st-form/st-form.component.ts
  src/theme/components/_form-base.scss
  src/theme/components/_form.scss
Labels: feature

#581 fix(changelog)[NA]: Fix changelog
  CHANGELOG.md
Labels: bug, documentation

#582 feat(st-form)[UX-99]: Allow to display and hide fields according to the value of another field
  CHANGELOG.md
  src/egeo-demo/st-form-demo/json-schema.ts
  src/lib/st-form/spec/st-form.component.spec.ts
  src/lib/st-form/st-form.component.html
  src/lib/st-form/st-form.component.ts
Labels: feature

#583 style(several components)[UX-75]: Apply visual changes for contrast improvements
  CHANGELOG.md
  src/egeo-demo/st-form-demo/json-schema.ts
  src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.html
  src/egeo-demo/st-textarea-demo/st-textarea-demo.html
  src/lib/st-foreground-notifications/st-foreground-notifications.scss
  src/lib/st-form/README.md
  src/lib/st-form/st-form.component.html
  src/lib/st-form/st-form.component.ts
  src/theme/components/_button.scss
  src/theme/components/_checkbox.scss
  src/theme/components/_foreground-notifications.scss
  src/theme/components/_form-base.scss
  src/theme/components/_form-list.scss
  src/theme/components/_index.scss
  src/theme/components/_radio.scss
  src/theme/components/_search.scss
  src/theme/components/_select.scss
  src/theme/components/_switch.scss
  src/theme/components/_tag-input.scss
  src/theme/utils/_forms.scss
Labels: style

#585 [NA] fix(st-draggable-card): Fix st-draggable-card delay and performance
  CHANGELOG.md
  src/egeo-demo/st-draggable-card-demo/st-draggable-card-demo.component.html
  src/egeo-demo/st-draggable-card-demo/st-draggable-card-demo.component.ts
  src/lib/st-draggable-card/st-draggable-card.component.spec.ts
  src/lib/st-draggable-card/st-draggable-card.component.ts
Labels: bug

#587 Prepare for 8.9.0 release
  CHANGELOG.md
  pom.xml
Labels: release

#588 feat(st-form)[NA]: Remove e.g from placeholders
  CHANGELOG.md
  src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  src/lib/st-form/st-form-field/st-form-field.component.ts
Labels: feature

#590 [NA]feat(st-select): Allow to add maximum of items before scrolling
  CHANGELOG.md
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.spec.ts
  src/lib/st-select/st-select.ts
Labels: feature

#592 cherry-pick from 9.0.0
  src/lib/st-tree/st-tree.component.html
  src/lib/st-tree/st-tree.component.scss
  src/theme/components/_tree.scss
Labels: cherry-pick

#594 fix(st-form)[NA]: Fix validations of nested properties
  CHANGELOG.md
  src/lib/st-form/st-form.component.ts
Labels: bug

#595 [NA]fix(st-foreground-notifications): Two way binding for visible input
  CHANGELOG.md
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.html
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.ts
Labels: bug

#596 refactor(st-tree)[NA]: Increment test coverage
  CHANGELOG.md
  src/egeo-demo/st-tree-demo/st-tree-demo.ts
  src/lib/st-tree/README.md
  src/lib/st-tree/st-tree.component.html
  src/lib/st-tree/st-tree.component.spec.ts
  src/lib/st-tree/st-tree.component.ts
  src/lib/st-tree/st-tree.model.ts
  src/theme/components/_form.scss
Labels: refactor, test

#597 [NA]fix(st-from)setting form as Pristine
  CHANGELOG.md
  src/egeo-demo/st-form-demo/json-schema.ts
  src/lib/st-form/st-form.component.ts
Labels: bug

#598 fix(st-sidebar)[NA]: Remove internal modification of the active item
  CHANGELOG.md
  src/lib/st-sidebar/st-sidebar.component.spec.ts
  src/lib/st-sidebar/st-sidebar.component.ts
Labels: bug

#599 fix(st-sidebar)[NA]: Fix stateless sidebar
  CHANGELOG.md
  pom.xml
  src/lib/st-sidebar/st-sidebar.component.spec.ts
  src/lib/st-sidebar/st-sidebar.component.ts
Labels: bug

#600 fix(st-form)[SAAS-57]: Fix performance when there are fields with ui attribute 'visible'
  CHANGELOG.md
  src/lib/st-form-list/spec/st-form-list.component.spec.ts
  src/lib/st-form-list/st-form-list.component.ts
  src/lib/st-form/st-form-field/st-form-field.component.ts
  src/lib/st-form/st-form.component.ts
Labels: bug

#601 Fix changelog to release 10.0.1
  CHANGELOG.md
Labels: documentation

#603 [cherry-pick]: Fix performance when there are fields with ui attribute 'visible'
  CHANGELOG.md
  src/lib/st-form-list/spec/st-form-list.component.spec.ts
  src/lib/st-form-list/st-form-list.component.ts
  src/lib/st-form/st-form-field/st-form-field.component.ts
  src/lib/st-form/st-form.component.ts
Labels: bug, cherry-pick

#604 [NA]feat(st-form): Allow to enable or disable tooltips
  CHANGELOG.md
  src/lib/st-form/README.md
  src/lib/st-form/spec/st-form.component.spec.ts
  src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  src/lib/st-form/st-form-field/st-form-field.component.ts
  src/lib/st-form/st-form.component.html
  src/lib/st-form/st-form.component.ts
Labels: feature
