Repository Stratio/egeo, pull requests merged in 2018-11, with the labels that each got.

#685 [SAAS-675] doc(st-form): Improve dynamic form demo in order to allow user to interact with it
  src/egeo-demo/st-form-demo/form-editor/json-schema.ts
  src/egeo-demo/st-form-demo/form-editor/st-form-editor-demo.component.scss
  src/egeo-demo/st-form-demo/form-editor/st-form-editor-demo.html
  src/egeo-demo/st-form-demo/form-editor/st-form-editor-demo.ts
  src/egeo-demo/st-form-demo/json-schema.ts
  src/egeo-demo/st-form-demo/st-form-demo.component.scss
  src/egeo-demo/st-form-demo/st-form-demo.html
  src/egeo-demo/st-form-demo/st-form-demo.module.ts
  src/egeo-demo/st-form-demo/st-form-demo.ts
  src/egeo-demo/st-form-demo/visual-field-improvements/st-visual-field-improvements-demo.component.scss
  src/egeo-demo/st-form-demo/visual-field-improvements/st-visual-field-improvements-editor-demo.html
  src/egeo-demo/st-form-demo/visual-field-improvements/st-visual-field-improvements-editor-demo.ts
  src/egeo-demo/st-form-demo/visual-section-improvements/st-visual-section-improvements-demo.component.scss
  src/egeo-demo/st-form-demo/visual-section-improvements/st-visual-section-improvements-editor-demo.html
  src/egeo-demo/st-form-demo/visual-section-improvements/st-visual-section-improvements-editor-demo.ts
Labels: demo

#688 [EGE-440] feat(st-tag-input): Allow to force validations
  CHANGELOG.md
  src/egeo-demo/st-tag-input-demo/st-tag-input-demo.component.html
  src/lib/st-tag-input/README.md
  src/lib/st-tag-input/st-tag-input.component.html
  src/lib/st-tag-input/st-tag-input.component.spec.ts
  src/lib/st-tag-input/st-tag-input.component.ts
Labels: feature

#686 [EGE-433]feat(Global): Replace deprecated dependency with ngx-virtual-scroller
  .classpath
  CHANGELOG.md
  package.json
  src/demo-app/tsconfig-build.json
  src/lib/package.json
  src/lib/st-item-list/item-list-scroll/item-list-scroll.component.html
  src/lib/st-item-list/item-list-scroll/item-list-scroll.component.scss
  src/lib/st-item-list/item-list-scroll/item-list-scroll.component.spec.ts
  src/lib/st-item-list/st-item-list.component.spec.ts
  src/lib/st-item-list/st-item-list.module.ts
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.spec.ts
  src/lib/st-two-list-selection/list-selection/list-selection.component.spec.ts
  src/lib/st-two-list-selection/st-two-list-selection.component.spec.ts
  src/lib/st-two-list-selection/st-two-list-selection.module.ts
  src/lib/st-two-list-selection/st-two-list-selection.view.component.spec.ts
  tools/package-tools/rollup-helpers.ts
Labels: feature

#687 [SECTY-663] feat(st-two-list, st-pagination): Improve st-two-list to show spinner when scroll down in lists. Include new event emitter in st-pagination
  CHANGELOG.md
  src/egeo-demo/st-pagination-demo/st-pagination-demo.component.html
  src/egeo-demo/st-pagination-demo/st-pagination-demo.component.ts
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.html
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.ts
  src/lib/st-pagination/README.md
  src/lib/st-pagination/st-pagination.component.ts
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.spec.ts
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.ts
  src/lib/st-two-list-selection/list-selection/list-selection.component.html
  src/lib/st-two-list-selection/list-selection/list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.model.ts
  src/lib/st-two-list-selection/st-two-list-selection.module.ts
  src/lib/st-two-list-selection/st-two-list-selection.ts
  src/lib/st-two-list-selection/st-two-list-selection.view.component.html
  src/lib/st-two-list-selection/st-two-list-selection.view.component.spec.ts
  src/lib/st-two-list-selection/st-two-list-selection.view.component.ts
Labels: feature

#690 [EGE-436] (st-text-area): fix error style
  CHANGELOG.md
  src/lib/st-textarea/st-textarea.component.scss
Labels: bug

#692 [EGE-436] (st-text-area): fix error style
  CHANGELOG.md
  src/lib/st-textarea/st-textarea.component.scss
Labels: bug, cherry-pick

#689 feat(st-foreground-notifications): new redesign
  CHANGELOG.md
  pom.xml
  src/demo-app/styles.scss
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.html
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.scss
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.component.ts
  src/egeo-demo/st-foreground-notifications-demo/st-foreground-notifications-demo.module.ts
  src/lib/public_api.ts
  src/lib/st-foreground-notifications/README.md
  src/lib/st-foreground-notifications/st-foreground-notifications.html
  src/lib/st-foreground-notifications/st-foreground-notifications.model.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.scss
  src/lib/st-foreground-notifications/st-foreground-notifications.spec.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.ts
  src/theme/components/_foreground-notifications.scss
Labels: enhancement
