Repository Stratio/egeo, pull requests merged in 2018-08, with the labels that each got.

#635 [SAAS-424] feat(icons): Update stratio font icon library
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: feature

#637 [SAAS-426] feat(st-button):Add small button style
  CHANGELOG.md
  src/egeo-demo/st-button-demo/st-button-demo.component.html
  src/theme/components/_button.scss
  src/theme/constants/_colors.scss
Labels: feature

#638 [SAAS-431,432,433,434,435,436] feat(StInput, StTextArea, StSelect, StTagInput, StCheckbox, StRadio): New disabled style
  CHANGELOG.md
  src/egeo-demo/st-input-demo/st-input-demo.ts
  src/theme/components/_checkbox.scss
  src/theme/components/_form-base.scss
  src/theme/components/_radio.scss
  src/theme/components/_select.scss
  src/theme/components/_tag-input.scss
Labels: feature

#626 [SECTY-436] feat( st-two-list): includes checkbox all button
  CHANGELOG.md
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.html
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.ts
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.spec.ts
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.ts
  src/lib/st-two-list-selection/list-selection/list-selection.component.html
  src/lib/st-two-list-selection/list-selection/list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.model.ts
  src/lib/st-two-list-selection/st-two-list-selection.spec.ts
  src/lib/st-two-list-selection/st-two-list-selection.ts
  src/lib/st-two-list-selection/st-two-list-selection.view.component.html
  src/lib/st-two-list-selection/st-two-list-selection.view.component.ts
Labels: feature

#639 [SAAS-437] feat(StBreadCrumb): Update breadcrumb to allow icons
  CHANGELOG.md
  src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.html
  src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.ts
  src/lib/public_api.ts
  src/lib/st-breadcrumbs/README.md
  src/lib/st-breadcrumbs/st-breadcrumbs-item/st-breadcrumbs-item.component.html
  src/lib/st-breadcrumbs/st-breadcrumbs.component.html
  src/lib/st-breadcrumbs/st-breadcrumbs.component.spec.ts
  src/lib/st-breadcrumbs/st-breadcrumbs.component.ts
  src/lib/st-breadcrumbs/st-breadcrumbs.interface.ts
Labels: feature

#641 [SAAS-437] feat(StBreadCrumb): Add ID parameter to the model
  src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.ts
  src/lib/st-breadcrumbs/README.md
  src/lib/st-breadcrumbs/st-breadcrumbs-item/st-breadcrumbs-item.component.spec.ts
  src/lib/st-breadcrumbs/st-breadcrumbs.component.spec.ts
  src/lib/st-breadcrumbs/st-breadcrumbs.component.ts
  src/lib/st-breadcrumbs/st-breadcrumbs.interface.ts
Labels: feature

#642 [secty 436] new improvements st two list
  src/lib/st-two-list-selection/st-two-list-selection.ts
Labels: cherry-pick, feature

#643 [SAAS-439] feat(StModal):Set default max and min width
  CHANGELOG.md
  src/egeo-demo/st-modal-demo/st-modal-demo.component.ts
  src/lib/st-modal/st-modal.component.spec.ts
  src/lib/st-modal/st-modal.component.ts
  src/lib/st-modal/st-modal.model.ts
  src/lib/st-modal/st-modal.service.spec.ts
  src/lib/st-modal/st-modal.service.ts
Labels: feature

#644 [NA] chore(release): Prepare changelog and pom for release 12.0.0
  CHANGELOG.md
  pom.xml
Labels: release

#645 [SAAS-448] feat(st-sidebar): Allow to add any content from outside to header and footer
  CHANGELOG.md
  src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.html
  src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.scss
  src/lib/st-sidebar/st-sidebar.component.html
  src/lib/st-sidebar/st-sidebar.component.spec.ts
Labels: feature

#646 [NA] feat(st-dropdown-menu): Allow to add a visual mode in order to display it as option or menu list
  CHANGELOG.md
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.html
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
  src/lib/public_api.ts
  src/lib/st-breadcrumbs/README.md
  src/lib/st-breadcrumbs/st-breadcrumbs.component.ts
  src/lib/st-dropdown-menu/README.md
  src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
  src/lib/st-sidebar/st-sidebar.component.spec.ts
  src/theme/components/_dropdown-menu.scss
Labels: feature
