Repository Stratio/egeo, pull requests merged in 2019-10, with the labels that each got.

#809 [NA] feat(st-select, st-dropdown-menu): Allow to show a spinner and capture event when scroll reaches the end
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.html
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.ts
  projects/egeo/src/lib/st-dropdown-menu/README.md
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.module.ts
  projects/egeo/src/lib/st-select/st-select.html
  projects/egeo/src/lib/st-select/st-select.ts
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: feature

#810 fix(st-select): when options changes update filteredOptions too
  CHANGELOG.md
  projects/egeo/src/lib/st-select/st-select.ts
Labels: bug

#811 [EGE-508] feat(st-fullscreen): Allow to display it on full width
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.html
  projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.module.ts
  projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.scss
  projects/egeo-demo/src/app/demos/st-fullscreen-layout-demo/st-fullscreen-layout-demo.ts
  projects/egeo/src/lib/st-fullscreen-layout/README.md
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.html
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.spec.ts
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.ts
  projects/egeo/src/theme/components/_fullscreen-layout.scss
Labels: feature

#812 [NA]feat(egeo-theme): Update icon font
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: feature

#813 [NA]feat(egeo-theme): Updated icon font to 1.22
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
Labels: feature

#817 [NA] feat(st-fullscreen):Add background color with full width
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.html
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.spec.ts
  projects/egeo/src/theme/components/_fullscreen-layout.scss
Labels: cherry-pick

#818 [NA] chore(changelog): update changelog
  CHANGELOG.md
Labels: release

#814 Cherry-pick [NA]feat(egeo-theme): Updated icon font to 1.22
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: cherry-pick

#820 [NA]fix(fullscreen): changes in fixed padding
  CHANGELOG.md
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.scss
  projects/egeo/src/theme/components/_fullscreen-layout.scss
Labels: style
