Repository Stratio/egeo, pull requests merged in 2019-03, with the labels that each got.

#724 [EGE-480] feat(st-search): Allow to differentiate search events by its origin
  CHANGELOG.md
  angular.json
  src/lib/public_api.ts
  src/lib/st-search/st-search.component.spec.ts
  src/lib/st-search/st-search.component.ts
  src/lib/st-search/st-search.model.ts
Labels: feature

#725 [NA] fix(styles): Add missing font family to some components
  src/theme/components/_breadcrumbs.scss
  src/theme/components/_horizontal-tabs.scss
  src/theme/components/_table.scss
Labels: bug, style

#726 [EGE-481] feat(st-dropdown-menu, st-search): Allow to display texts with HTML tags and display message when autocomplete list does not have items
  CHANGELOG.md
  src/egeo-demo/st-search-demo/st-search-demo.ts
  src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
  src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.spec.ts
  src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
  src/lib/st-search/st-search.component.html
  src/lib/st-search/st-search.component.spec.ts
  src/lib/st-search/st-search.component.ts
  src/theme/components/_dropdown-menu.scss
Labels: feature

#727 [EGE-481] fix(st-search): When user selects an option from the autocomplete list, input is updated with the value of the selected option
  CHANGELOG.md
  src/lib/st-search/st-search.component.spec.ts
  src/lib/st-search/st-search.component.ts
Labels: bug

#728 [EGE-481] fix(st-search): When user selects an option from the autocomplete list, input is updated with the value of the selected option
  CHANGELOG.md
  src/lib/st-search/st-search.component.spec.ts
  src/lib/st-search/st-search.component.ts
Labels: bug, cherry-pick

#730 [DGPB-1948] feat(dropdown menu): Allow user to move through options using the keyboard arrows
  CHANGELOG.md
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.html
  src/egeo-demo/st-select-demo/select-demo.html
  src/lib/st-dropdown-menu/README.md
  src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
  src/lib/st-search/README.md
  src/lib/st-search/st-search.component.html
  src/lib/st-search/st-search.component.ts
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.ts
  src/theme/components/_dropdown-menu.scss
Labels: feature

#732 Update pom release version to 16.1.0
  pom.xml
Labels: bug, release

#733 [EGE-484] feat(icons): Update icon font
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  src/demo-app/app/modules/theme/icons-demo/icon-demo/icon-demo.scss
  src/demo-app/app/modules/theme/icons-demo/icons-demo.scss
  src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: style

#731 [EGE-485] feat(st-select): new design for the search of elements
  CHANGELOG.md
  src/egeo-demo/st-select-demo/select-demo.html
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.scss
  src/lib/st-select/st-select.spec.ts
  src/lib/st-select/st-select.ts
Labels: feature
