Repository Stratio/egeo, pull requests merged in 2019-11, with the labels that each got.

#816 [NA] feat(st-fullscreen):Add background color with full width
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.html
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.spec.ts
  projects/egeo/src/theme/components/_fullscreen-layout.scss
Labels: style

#822 [NA] feat(icon font): Update icon font to 1.24
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: style

#821 [NA]fix(fullscreen): changes in fixed padding
  CHANGELOG.md
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.scss
  projects/egeo/src/theme/components/_fullscreen-layout.scss
Labels: cherry-pick, style

#823 [NA]feat(st-menu): Create menu component
  CHANGELOG.md
  package.json
  projects/egeo-demo/src/app/demos/barrels.ts
  projects/egeo-demo/src/app/demos/demos.routes.ts
  projects/egeo-demo/src/app/demos/public_api.ts
  projects/egeo-demo/src/app/demos/st-menu-demo/st-menu-demo.component.html
  projects/egeo-demo/src/app/demos/st-menu-demo/st-menu-demo.component.scss
  projects/egeo-demo/src/app/demos/st-menu-demo/st-menu-demo.component.ts
  projects/egeo-demo/src/app/demos/st-menu-demo/st-menu-demo.module.ts
  projects/egeo-demo/src/app/modules/home/home.scss
  projects/egeo-demo/src/app/shared/menu/menu.ts
  projects/egeo/src/lib/barrels.ts
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-menu/st-menu-options/st-menu-options.component.html
  projects/egeo/src/lib/st-menu/st-menu-options/st-menu-options.component.scss
  projects/egeo/src/lib/st-menu/st-menu-options/st-menu-options.component.ts
  projects/egeo/src/lib/st-menu/st-menu.component.html
  projects/egeo/src/lib/st-menu/st-menu.component.scss
  projects/egeo/src/lib/st-menu/st-menu.component.spec.ts
  projects/egeo/src/lib/st-menu/st-menu.component.ts
  projects/egeo/src/lib/st-menu/st-menu.model.ts
  projects/egeo/src/lib/st-menu/st-menu.module.ts
  projects/egeo/src/theme/constants/_settings.scss
  projects/egeo/src/theme/utils/_index.scss
  projects/egeo/src/theme/utils/_other.scss
Labels: feature, new component
