Repository Stratio/egeo, pull requests merged in 2019-08, with the labels that each got.

#771 [NA]fix(st-header): Fixed st-header active option
  CHANGELOG.md
  src/lib/st-header/menu-option/menu-option.html
  src/lib/st-header/menu-option/menu-option.spec.ts
  src/lib/st-header/menu-option/menu-option.ts
Labels: bug

#773 [NA] chore(icon font): Update to 1.14 and lodash to 4.17.13
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  package.json
  pom.xml
  projects/egeo/package.json
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: UX, enhancement

#775 [NA]fix(egeo): Fix release task
  tools/gulp/tasks/egeo-publish.ts
Labels: bug

#776 [NA]fix(egeo): Fix release destination folder
  tools/gulp/tasks/egeo-publish.ts
Labels: bug

#777 [NA]fix(egeo): Fixed egeo version replace and licence copy
  package.json
  tools/gulp/package-tools/build-config.ts
  tools/gulp/package-tools/build-release.ts
  tools/gulp/package-tools/copy-files.ts
  tools/gulp/package-tools/package-versions.ts
  tools/gulp/tasks/egeo-publish.ts
  tools/gulp/tasks/others.ts
Labels: bug

#779 [NA]feat(egeo-theme): Updated icon font
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: feature

#780 [NA]fix(egeo): Added package.json to egeo-demo project
  angular.json
  projects/egeo-demo/src/package.json
Labels: bug

#781 [NA]fix(egeo): Fixed egeo package.json copy
  projects/egeo/package.json
  tools/gulp/package-tools/build-release.ts
Labels: bug

#785 [NA] Fixed package.json main config
  CHANGELOG.md
  projects/egeo/src/lib/package.json
Labels: bug

#787 [NA] cherry-pick: fix package.json (construction task)
  CHANGELOG.md
  projects/egeo/package.json
  projects/egeo/src/lib/package.json
  tools/gulp/package-tools/build-release.ts
Labels: cherry-pick

#789 [NA] fix(theme): fix st-widget imports
  CHANGELOG.md
  projects/egeo/package.json
  projects/egeo/src/theme/components/_widget.scss
Labels: bug

#790 [NA] cherry-pick: fix(theme) - fix st-widget imports
  CHANGELOG.md
  projects/egeo/package.json
  projects/egeo/src/theme/components/_widget.scss
Labels: cherry-pick
