Repository Stratio/egeo, pull requests merged in 2019-05, with the labels that each got.

#749 [NA]refactor(egeo): Removed old components
  CHANGELOG.md
  src/egeo-demo/barrels.ts
  src/egeo-demo/egeo-demo.routes.ts
  src/egeo-demo/public_api.ts
  src/egeo-demo/st-help-demo/st-help-demo.component.html
  src/egeo-demo/st-help-demo/st-help-demo.component.scss
  src/egeo-demo/st-help-demo/st-help-demo.component.ts
  src/egeo-demo/st-help-demo/st-help-demo.module.ts
  src/egeo-demo/st-info-card-demo/st-info-card-demo.html
  src/egeo-demo/st-info-card-demo/st-info-card-demo.module.ts
  src/egeo-demo/st-info-card-demo/st-info-card-demo.scss
  src/egeo-demo/st-info-card-demo/st-info-card-demo.ts
  src/egeo-demo/st-tab-box-demo/st-tab-box-demo.html
  src/egeo-demo/st-tab-box-demo/st-tab-box-demo.module.ts
  src/egeo-demo/st-tab-box-demo/st-tab-box-demo.scss
  src/egeo-demo/st-tab-box-demo/st-tab-box-demo.ts
  src/egeo-demo/st-tip-demo/st-tip-demo.component.html
  src/egeo-demo/st-tip-demo/st-tip-demo.component.scss
  src/egeo-demo/st-tip-demo/st-tip-demo.component.ts
  src/egeo-demo/st-tip-demo/st-tip-demo.module.ts
  src/egeo-demo/st-tree-demo/st-tree-demo.html
  src/egeo-demo/st-tree-demo/st-tree-demo.module.ts
  src/egeo-demo/st-tree-demo/st-tree-demo.scss
  src/egeo-demo/st-tree-demo/st-tree-demo.ts
  src/lib/barrels.ts
  src/lib/public_api.ts
  src/lib/st-help/st-help.component.html
  src/lib/st-help/st-help.component.scss
  src/lib/st-help/st-help.component.spec.ts
  src/lib/st-help/st-help.component.ts
  src/lib/st-help/st-help.module.ts
  src/lib/st-info-card/st-info-card.component.html
  src/lib/st-info-card/st-info-card.component.scss
  src/lib/st-info-card/st-info-card.component.spec.ts
  src/lib/st-info-card/st-info-card.component.ts
  src/lib/st-info-card/st-info-card.module.ts
  src/lib/st-tab-box/st-tab-box.component.html
  src/lib/st-tab-box/st-tab-box.component.scss
  src/lib/st-tab-box/st-tab-box.component.spec.ts
  src/lib/st-tab-box/st-tab-box.component.ts
  src/lib/st-tab-box/st-tab-box.interface.ts
  src/lib/st-tab-box/st-tab-box.module.ts
  src/lib/st-tip/st-tip.component.html
  src/lib/st-tip/st-tip.component.scss
  src/lib/st-tip/st-tip.component.spec.ts
  src/lib/st-tip/st-tip.component.ts
  src/lib/st-tip/st-tip.module.ts
  src/lib/st-tree/README.md
  src/lib/st-tree/st-tree.component.html
  src/lib/st-tree/st-tree.component.scss
  src/lib/st-tree/st-tree.component.spec.ts
  src/lib/st-tree/st-tree.component.ts
  src/lib/st-tree/st-tree.model.ts
  src/lib/st-tree/st-tree.module.ts
  src/theme/components/_help.scss
  src/theme/components/_index.scss
  src/theme/components/_info-card.scss
  src/theme/components/_tab-box.scss
  src/theme/components/_tip.scss
  src/theme/components/_tree.scss
Labels: refactor

#744 [EGE-434]feat(st-modal2): New modal component
  CHANGELOG.md
  src/demo-app/app/shared/menu/menu.scss
  src/demo-app/styles.scss
  src/egeo-demo/barrels.ts
  src/egeo-demo/egeo-demo.routes.ts
  src/egeo-demo/st-modal2-demo/st-modal2-demo.component.html
  src/egeo-demo/st-modal2-demo/st-modal2-demo.component.scss
  src/egeo-demo/st-modal2-demo/st-modal2-demo.component.ts
  src/egeo-demo/st-modal2-demo/st-modal2-demo.module.ts
  src/lib/barrels.ts
  src/lib/public_api.ts
  src/lib/st-modal/st-modal-buttons/st-modal-buttons.ts
  src/lib/st-modal/st-modal.component.spec.ts
  src/lib/st-modal2/st-modal2.component.html
  src/lib/st-modal2/st-modal2.component.scss
  src/lib/st-modal2/st-modal2.component.spec.ts
  src/lib/st-modal2/st-modal2.component.ts
  src/lib/st-modal2/st-modal2.module.ts
Labels: blocked, new component

#751 [NA]feat(icon_stratio): Update icons font
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: feature

#752 refactor(egeo): Fix method calls from templates
  CHANGELOG.md
  src/lib/st-alerts/alert-box/st-alert-box.component.html
  src/lib/st-alerts/alert-box/st-alert-box.component.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.html
  src/lib/st-foreground-notifications/st-foreground-notifications.ts
  src/lib/st-info-box/st-info-box.component.html
  src/lib/st-info-box/st-info-box.component.ts
  src/lib/st-input/st-input.component.html
  src/lib/st-input/st-input.component.ts
  src/lib/st-modal/st-modal-buttons/st-modal-buttons.html
  src/lib/st-modal/st-modal-buttons/st-modal-buttons.ts
  src/lib/st-page-title/st-page-title.component.html
  src/lib/st-page-title/st-page-title.component.ts
  src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.html
  src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.ts
  src/lib/st-spinner/st-spinner.component.html
  src/lib/st-spinner/st-spinner.component.spec.ts
  src/lib/st-spinner/st-spinner.component.ts
  src/lib/st-table/shared/st-table-row/st-table-row.component.scss
  src/lib/st-tag-input/st-tag-input.component.html
  src/lib/st-tag-input/st-tag-input.component.spec.ts
  src/lib/st-tag-input/st-tag-input.component.ts
  src/lib/st-textarea/st-textarea.component.html
  src/lib/st-textarea/st-textarea.component.ts
Labels: refactor

#755 [EGE-496] feat(st-horizontal-tabs): Allow to insert content from outside after tabs
  CHANGELOG.md
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.html
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.scss
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.ts
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.module.ts
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.html
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.scss
Labels: feature

#754 [EGE-496] feat(st-filter-selector): Allow to display menu aligned to the right
  CHANGELOG.md
  src/egeo-demo/st-filter-selector-demo/st-filter-selector-demo.component.html
  src/lib/st-dropdown-menu/README.md
  src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
  src/lib/st-filter-selector/README.md
  src/lib/st-filter-selector/st-filter-selector.component.ts
  src/lib/st-filter-selector/st-filter-selector.style.scss
  src/lib/st-filter-selector/st-filter-selector.template.html
  src/lib/st-pop/README.md
  src/lib/st-pop/st-pop.component.spec.ts
  src/lib/st-pop/st-pop.component.ts
  src/lib/st-search/st-search.component.spec.ts
  src/lib/st-table/shared/st-table-row/st-table-row.component.scss
Labels: feature
