Repository Stratio/egeo, pull requests merged in 2019-09, with the labels that each got.

#792 [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to fix compatibility error with internal library tweenjs
  CHANGELOG.md
  package.json
Labels: bug

#793 [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to fix compatibility error with internal library tweenjs
  CHANGELOG.md
  package.json
Labels: bug, cherry-pick

#794 Cherry pick [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to fix compatibility error with internal library tweenjs
  CHANGELOG.md
  package.json
Labels: bug, cherry-pick

#795 Cherry pick [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to fix compatibility error with internal library tweenjs
  CHANGELOG.md
  package.json
Labels: bug, cherry-pick

#796 [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to in the internal package.json file
  src/lib/package.json
Labels: bug

#797 [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to in the internal package.json
  src/lib/package.json
Labels: bug, cherry-pick

#798 [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to in the internal package.json
  projects/egeo/package.json
Labels: bug, cherry-pick

#799 [NA] fix(ngx-virtual-scroller): Put version to 3.0.2 to in the internal package.json
  projects/egeo/package.json
Labels: bug, cherry-pick

#800 [NA] fix(build): Remove unused dependencies and fix public api export
  package.json
  projects/egeo/src/public_api.ts
Labels: bug, build

#801 Cherry pick [NA] fix(build): Remove unused dependencies and fix public api export
  CHANGELOG.md
  package.json
  projects/egeo/src/public_api.ts
Labels: bug, build

#802 [NA] fix(st-notifications): Fix refreshing notification statuses
  CHANGELOG.md
  src/lib/st-foreground-notifications/st-foreground-notifications.ts
Labels: bug

#803 [NA] fix(st-notifications): Fix refreshing notification statuses
  CHANGELOG.md
  projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.ts
Labels: bug, cherry-pick

#804 [EGE-505] feat(st-dropdown-menu): Allow to display a text info below label
  CHANGELOG.md
  angular.json
  pom.xml
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.component.scss
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.spec.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: feature

#805 [EGE-506] feat(st-bubble): Allow to disable or enable animation and small theme and added functionality to open to left or right
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.html
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.scss
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.ts
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.module.ts
  projects/egeo/src/lib/st-bubble/st-bubble.component.html
  projects/egeo/src/lib/st-bubble/st-bubble.component.spec.ts
  projects/egeo/src/lib/st-bubble/st-bubble.component.ts
  projects/egeo/src/theme/components/_bubble.scss
Labels: feature

#806 [NA] fix(st-bubble): Center text when it is shorter than bubble's width
  projects/egeo/src/lib/st-bubble/st-bubble.component.scss
Labels: style

#807 [NA] chore(package): Put version to 3.0.2 to fix compatibility error with internal library tweenjs
  CHANGELOG.md
  package.json
  src/lib/package.json
Labels: bug
