Repository Stratio/egeo, pull requests merged in 2019-04, with the labels that each got.

#735 [NA] fix(st-select): set item clicked correctly after filtering list
  src/lib/st-select/st-select.ts
Labels: bug

#736 [EGE-486] feat(search): Allow to hide or show loupe icon
  CHANGELOG.md
  src/egeo-demo/st-search-demo/st-search-demo.html
  src/lib/st-search/README.md
  src/lib/st-search/st-search.component.html
  src/lib/st-search/st-search.component.spec.ts
  src/lib/st-search/st-search.component.ts
Labels: feature

#737 [EGE-487] feat(filter selector): Do not change the icon when menu is open
  CHANGELOG.md
  src/lib/st-filter-selector/README.md
  src/lib/st-filter-selector/st-filter-selector.component.spec.ts
  src/lib/st-filter-selector/st-filter-selector.component.ts
  src/lib/st-filter-selector/st-filter-selector.style.scss
  src/lib/st-filter-selector/st-filter-selector.template.html
Labels: feature

#738 [EGE-488] fix(select): Fix error message format
  CHANGELOG.md
  src/egeo-demo/st-select-demo/select-demo.html
  src/egeo-demo/st-select-demo/select-demo.ts
  src/lib/st-select/st-check-validations.ts
  src/lib/st-select/st-select.html
  src/lib/st-select/st-select.spec.ts
  src/lib/st-select/st-select.ts
  src/theme/components/_sidebar.scss
Labels: bug

#739 [NA] fix(table): Put pointer cursor to clickable cell´s children and not to entire cell
  CHANGELOG.md
  src/theme/components/_table.scss
Labels: bug, style

#740 [NA] fix(breadcrumbs): Do not display capitalized text
  CHANGELOG.md
  src/theme/components/_breadcrumbs.scss
Labels: bug, style

#741 [NA] chore(dependencies): Upgrade lodash to 4.17.11
  CHANGELOG.md
  package.json
  src/lib/package.json
Labels: enhancement

#742 [EGE-490]: fix(st-table): Border disappears when user puts the mouse over the row
  CHANGELOG.md
  src/theme/components/_table.scss
Labels: bug

#743 [Cherry pick][EGE-490]: fix(st-table): Border disappears when user puts the mouse over the row
  CHANGELOG.md
  src/theme/components/_table.scss
Labels: bug, cherry-pick

#746 [EGE-491] feat(zero page): Create component
  CHANGELOG.md
  src/demo-app/assets/images/empty-box-icon.svg
  src/demo-app/assets/images/variable-icon.svg
  src/egeo-demo/barrels.ts
  src/egeo-demo/egeo-demo.routes.ts
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.component.html
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.component.scss
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.component.ts
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.module.ts
  src/lib/barrels.ts
  src/lib/public_api.ts
  src/lib/st-zero-page/README.md
  src/lib/st-zero-page/st-zero-page.component.spec.ts
  src/lib/st-zero-page/st-zero-page.component.ts
  src/lib/st-zero-page/st-zero-page.module.ts
  src/lib/st-zero-page/st-zero-page.style.scss
  src/lib/st-zero-page/st-zero-page.template.html
  src/theme/components/_index.scss
  src/theme/components/_zero-page.scss
Labels: feature

#745 [NA]feat(icon_stratio): Update icons font
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
Labels: enhancement

#747 [EGE-493] style(st-table): Align cell content to the top when there are long texts
  CHANGELOG.md
  src/egeo-demo/st-table-demo/st-table-demo.component.scss
  src/lib/st-table/shared/st-table-cell/st-table-cell.component.scss
  src/lib/st-table/shared/st-table-row/st-table-row.component.scss
  src/theme/components/_table.scss
Labels: style

#748 chore(demo): remove st-info-box
  CHANGELOG.md
  src/egeo-demo/egeo-demo.routes.ts
Labels: demo
