Repository Stratio/egeo, pull requests merged in 2019-12, with the labels that each got.

#825 [NA] feat(grid): Allow to customize max-width with a css variable
  CHANGELOG.md
  projects/egeo/src/lib/st-header/st-header.component.html
  projects/egeo/src/theme/components/_header.scss
  projects/egeo/src/theme/grid/grid.scss
Labels: feature

#824 [NA]feat(egeo-theme): Update icon font
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: enhancement

#826 [NA] feat(progress-bar): add input for a wider bar option
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-progress-bar-demo/st-progress-bar-demo.component.html
  projects/egeo-demo/src/app/demos/st-progress-bar-demo/st-progress-bar-demo.component.scss
  projects/egeo/src/lib/st-progress-bar/README.md
  projects/egeo/src/lib/st-progress-bar/st-progress-bar.scss
  projects/egeo/src/lib/st-progress-bar/st-progress-bar.ts
Labels: feature

#829 [EGE-510] feat(st-input): Allow to display an autocomplete list in order to select a predefined text
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
  projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.ts
  projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  projects/egeo/src/lib/st-input/README.md
  projects/egeo/src/lib/st-input/st-input.component.html
  projects/egeo/src/lib/st-input/st-input.component.spec.ts
  projects/egeo/src/lib/st-input/st-input.component.ts
  projects/egeo/src/lib/st-input/st-input.module.ts
  projects/egeo/src/theme/components/_input.scss
Labels: feature

#828 [NA]feat(egeo-demo): Egeo demo layout improvements
  projects/egeo-demo/src/app/app.component.html
  projects/egeo-demo/src/app/app.component.scss
  projects/egeo-demo/src/app/modules/demos/demo-layout/demo.layout.scss
  projects/egeo-demo/src/app/modules/home/home.scss
  projects/egeo-demo/src/app/modules/theme/colors/colors.html
  projects/egeo-demo/src/app/modules/theme/colors/colors.scss
  projects/egeo-demo/src/app/modules/theme/fonts/fonts.html
  projects/egeo-demo/src/app/modules/theme/fonts/fonts.scss
  projects/egeo-demo/src/app/modules/theme/icons-demo/icons-demo.html
  projects/egeo-demo/src/app/modules/theme/icons-demo/icons-demo.scss
  projects/egeo-demo/src/app/shared/menu/menu.scss
  projects/egeo-demo/src/styles.scss
  projects/egeo/src/lib/st-menu/st-menu-options/st-menu-options.component.scss
  projects/egeo/src/lib/utils/demo-generator/demo-generator.ts
Labels: enhancement, feature

#831 [NA] chore(lodash): Update version to 4.17.13 in served package.json
  projects/egeo/src/lib/package.json
Labels: enhancement
