Repository Stratio/egeo, pull requests merged in 2019-07, with the labels that each got.

#765 [NA] feat(color picker): Implement interface ControlValueAccessor in order to can be used as part of a form
  src/egeo-demo/st-color-picker-demo/st-color-picker-demo.html
  src/egeo-demo/st-color-picker-demo/st-color-picker-demo.module.ts
  src/egeo-demo/st-color-picker-demo/st-color-picker-demo.ts
  src/lib/st-color-picker/st-color-picker.component.spec.ts
  src/lib/st-color-picker/st-color-picker.component.ts
  src/lib/st-color-picker/st-color-picker.module.ts
Labels: feature

#766 [NA] styles(st-breadcrumbs): changed 'title mode' links color to default
  CHANGELOG.md
  src/theme/components/_breadcrumbs.scss
Labels: style

#767 [NA] chore(icon font): Update to version 1.12
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: UX, style

#768 [NA] feat(st-zero-page): Add ng-content to be able to display one or more buttons
  CHANGELOG.md
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.component.html
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.component.scss
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.component.ts
  src/egeo-demo/st-zero-page-demo/st-zero-page-demo.module.ts
  src/lib/st-zero-page/README.md
  src/lib/st-zero-page/st-zero-page.component.spec.ts
  src/lib/st-zero-page/st-zero-page.component.ts
  src/lib/st-zero-page/st-zero-page.style.scss
  src/lib/st-zero-page/st-zero-page.template.html
Labels: feature

#769 [EGE-499] feat(st-dropdown-menu): Allow to custom label and icon colors
  CHANGELOG.md
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.component.scss
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.html
  src/egeo-demo/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
  src/lib/st-dropdown-menu/README.md
  src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
  src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.spec.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
Labels: feature

#770 [NA]fix(st-foreground-notifications): Fix selected current notification
  CHANGELOG.md
  src/lib/st-foreground-notifications/st-foreground-notifications.spec.ts
  src/lib/st-foreground-notifications/st-foreground-notifications.ts
Labels: bug
