Repository Stratio/egeo, pull requests merged in 2019-06, with the labels that each got.

#756 [EGE-482] feat(st-toggle-buttons): Update styles
  CHANGELOG.md
  src/lib/st-toggle-buttons/st-toggle-buttons.component.html
  src/lib/st-toggle-buttons/st-toggle-buttons.component.scss
  src/lib/st-toggle-buttons/st-toggle-buttons.component.spec.ts
  src/lib/st-toggle-buttons/st-toggle-buttons.component.ts
  src/lib/st-toggle-buttons/st-toggle-buttons.interface.ts
  src/theme/components/_toggle-buttons.scss
Labels: refactor

#758 [NA] feat(icon font): Upgrade font
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: feature

#759 [NA]fix(st-tag-input): Now test if errorMessage is a string
  CHANGELOG.md
  src/lib/st-tag-input/st-tag-input.component.ts
Labels: bug

#761 [NA]fix(st-table): Fixed error with selectableAll and sortable columns
  CHANGELOG.md
  src/egeo-demo/st-table-demo/st-table-demo.component.html
  src/lib/st-table/st-table.component.html
  src/lib/st-table/st-table.component.scss
  src/theme/components/_table.scss
Labels: bug

#762 feat(st-two-list): EGE-497 shows dropdown if list is not editable.
  CHANGELOG.md
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.html
  src/egeo-demo/st-two-list-selection-demo/st-two-list-selection-demo.ts
  src/lib/st-two-list-selection/list-item/list-item.component.html
  src/lib/st-two-list-selection/list-item/list-item.component.scss
  src/lib/st-two-list-selection/list-item/list-item.component.spec.ts
  src/lib/st-two-list-selection/list-item/list-item.component.ts
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.scss
  src/lib/st-two-list-selection/list-scroll/list-scroll.component.ts
  src/lib/st-two-list-selection/list-selection/list-selection.component.html
  src/lib/st-two-list-selection/list-selection/list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.component.ts
  src/lib/st-two-list-selection/st-two-list-selection.model.ts
  src/lib/st-two-list-selection/st-two-list-selection.module.ts
  src/lib/st-two-list-selection/st-two-list-selection.view.component.html
  src/lib/st-two-list-selection/st-two-list-selection.view.component.ts
Labels: feature
