Repository Stratio/egeo, pull requests merged in 2019-01, with the labels that each got.

#706 [EGE-475] feat(filter-selector): Create filter selector component
  CHANGELOG.md
  src/egeo-demo/barrels.ts
  src/egeo-demo/egeo-demo.routes.ts
  src/egeo-demo/public_api.ts
  src/egeo-demo/st-filter-selector-demo/st-filter-selector-demo.component.html
  src/egeo-demo/st-filter-selector-demo/st-filter-selector-demo.component.scss
  src/egeo-demo/st-filter-selector-demo/st-filter-selector-demo.component.ts
  src/egeo-demo/st-filter-selector-demo/st-filter-selector-demo.module.ts
  src/lib/public_api.ts
  src/lib/st-filter-selector/README.md
  src/lib/st-filter-selector/st-filter-selector.component.spec.ts
  src/lib/st-filter-selector/st-filter-selector.component.ts
  src/lib/st-filter-selector/st-filter-selector.module.ts
  src/lib/st-filter-selector/st-filter-selector.style.scss
  src/lib/st-filter-selector/st-filter-selector.template.html
Labels: feature

#707 [EGE-475] style(filter-selector): Add minor style changes
  src/egeo-demo/st-filter-selector-demo/st-filter-selector-demo.component.scss
  src/lib/st-filter-selector/st-filter-selector.style.scss
Labels: style

#708 [NA] fix(prismjs): Fix dependency
  angular.json
  package.json
  src/lib/st-docs/st-prism/st-prism.component.ts
  test/karma.conf.js
Labels: bug

#709 [EGE-443] feat(table): Allow display tables with white and default themes
  CHANGELOG.md
  src/egeo-demo/st-table-demo/st-table-demo.component.html
  src/egeo-demo/st-table-demo/st-table-demo.component.scss
  src/egeo-demo/st-table-demo/st-table-demo.component.ts
  src/lib/st-table/README.md
  src/lib/st-table/shared/st-table-cell/st-table-cell.component.scss
  src/lib/st-table/st-table.component.html
  src/lib/st-table/st-table.component.scss
  src/lib/st-table/st-table.component.spec.ts
  src/lib/st-table/st-table.component.ts
  src/theme/components/_table.scss
Labels: feature

#710 [EGE-476] feat(horizontal tabs): Allow to add classes to tabs according to its status
  CHANGELOG.md
  src/egeo-demo/st-horizontal-tabs-demo/st-horizontal-tabs-demo.component.ts
  src/lib/public_api.ts
  src/lib/st-horizontal-tabs/README.md
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.html
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.spec.ts
  src/lib/st-horizontal-tabs/st-horizontal-tabs.component.ts
  src/lib/st-horizontal-tabs/st-horizontal-tabs.model.ts
  src/theme/components/_horizontal-tabs.scss
Labels: feature

#711 [EOS-1679] fix(st-sidebar): fix minor style bug
  CHANGELOG.md
  src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.ts
  src/theme/components/_sidebar.scss
Labels: bug

#712 [EOS-1679] fix(st-sidebar): fix minor style bug
  CHANGELOG.md
  src/egeo-demo/st-sidebar-demo/st-sidebar-demo.component.ts
  src/theme/components/_sidebar.scss
Labels: bug, cherry-pick

#714 [EGEO-443] feat(table): Revert changes in tables with fixed header
  CHANGELOG.md
  src/egeo-demo/st-table-demo/st-table-demo.component.html
  src/egeo-demo/st-table-demo/st-table-demo.component.scss
  src/lib/st-table/README.md
  src/lib/st-table/st-table.component.html
  src/lib/st-table/st-table.component.spec.ts
  src/lib/st-table/st-table.component.ts
Labels: Revert

#713 [EGEO-443] feat(table): Revert changes in tables with fixed header
  CHANGELOG.md
  src/egeo-demo/st-table-demo/st-table-demo.component.html
  src/egeo-demo/st-table-demo/st-table-demo.component.scss
  src/lib/st-table/README.md
  src/lib/st-table/st-table.component.html
  src/lib/st-table/st-table.component.spec.ts
  src/lib/st-table/st-table.component.ts
Labels: Revert

#716 [NA] fix(table): Remove transition for all attributes in order to prevent a wrong behaviour
  CHANGELOG.md
  src/lib/st-table/shared/st-table-row/st-table-row.component.scss
  src/theme/components/_table.scss
Labels: bug

#717 [NA] fix(table): Remove transition for all attributes in order to prevent a wrong behaviour
  CHANGELOG.md
  src/lib/st-table/shared/st-table-row/st-table-row.component.scss
  src/theme/components/_table.scss
Labels: bug

#718 [NA] fix(st-breadcrumb): breadcrumb with a long text displays displaced section
  CHANGELOG.md
  src/egeo-demo/st-breadcrumbs-demo/st-breadcrumbs-demo.html
  src/lib/st-breadcrumbs/st-breadcrumbs.component.scss
Labels: bug

#719 [EOS-1698] fix(st-modal): fix minor style bug
  CHANGELOG.md
  src/theme/components/_modal.scss
Labels: bug
