Repository Stratio/egeo, pull requests merged in 2020-03, with the labels that each got.

#865 [NA] fix(st-button): Set cursor pointer to button class
  CHANGELOG.md
  projects/egeo/src/theme/components/_button.scss
Labels: style

#867 [NA] style(color palette): Add color space-40
  CHANGELOG.md
  projects/egeo/src/theme/constants/_colors.scss
Labels: style

#866 [GS-1846] feat(st-table): Includes new field 'filterable' to apply filters
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-form-list-demo/st-form-list-demo.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.module.ts
  projects/egeo/src/lib/st-pop-over/st-pop-over.component.scss
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.scss
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.spec.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
  projects/egeo/src/lib/st-table/shared/table-header.interface.ts
  projects/egeo/src/lib/st-table/st-table.component.html
  projects/egeo/src/lib/st-table/st-table.component.scss
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.ts
  projects/egeo/src/lib/st-table/st-table.module.ts
  projects/egeo/src/theme/components/_checkbox.scss
  projects/egeo/src/theme/components/_pop-over.scss
  projects/egeo/src/theme/components/_table.scss
  projects/egeo/src/theme/constants/_fonts.scss
Labels: feature

#868 [NA] feat(st-bubble): Allow to add a min width from outside and cut words when there are longer than width
  CHANGELOG.md
  projects/egeo/src/lib/st-bubble/README.md
  projects/egeo/src/lib/st-bubble/st-bubble.component.html
  projects/egeo/src/lib/st-bubble/st-bubble.component.scss
  projects/egeo/src/lib/st-bubble/st-bubble.component.spec.ts
  projects/egeo/src/lib/st-bubble/st-bubble.component.ts
Labels: style

#870 [NA] style(icon font): Update version to 1.29
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: style

#871 [NA] feat(st-bubble): Allow to add a max width from outside and cut words when there are longer than that width
  CHANGELOG.md
  projects/egeo/src/lib/st-bubble/README.md
  projects/egeo/src/lib/st-bubble/st-bubble.component.html
  projects/egeo/src/lib/st-bubble/st-bubble.component.scss
  projects/egeo/src/lib/st-bubble/st-bubble.component.spec.ts
  projects/egeo/src/lib/st-bubble/st-bubble.component.ts
  projects/egeo/src/theme/components/_bubble.scss
Labels: feature

#874 [NA] feat(st-alerts): adapted to new style definition
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-alert-demo/st-alerts-demo.html
  projects/egeo-demo/src/app/demos/st-alert-demo/st-alerts-demo.ts
  projects/egeo/src/lib/st-alerts/alert-box/st-alert-box.component.html
  projects/egeo/src/lib/st-alerts/alert-box/st-alert-box.component.spec.ts
  projects/egeo/src/lib/st-alerts/alert-box/st-alert-box.component.ts
  projects/egeo/src/lib/st-alerts/st-alerts.model.ts
  projects/egeo/src/theme/components/_alerts.scss
Labels: enhancement

#875 [NA] style(icon font): Update version to 1.30
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
Labels: style

#877 [NA] fix(validator/clicloutside directives): Public directive modules in order to can be used from outside
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-input/st-input.module.ts
Labels: bug

#878 Cherry pick [NA] fix(validator/clicloutside directives): Public directive modules in order to can be used from outside
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-input/st-input.module.ts
Labels: bug, cherry-pick

#880 Cherry pick: [NA] fix(validator/clickoutside directives): Public directive modules in order to can be used from outside
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-input-demo/st-input-demo.html
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-input/st-input.module.ts
Labels: bug, cherry-pick
