Repository Stratio/egeo, pull requests merged in 2020-02, with the labels that each got.

#844 feat(st-select): apply new UX font size and color in forms
  CHANGELOG.md
  projects/egeo/src/theme/components/_form-base.scss
Labels: style

#845 [DGPB-3034] fix(st-modal): Do not break words
  CHANGELOG.md
  projects/egeo/src/theme/components/_modal.scss
Labels: bug, style

#847 [NA] fix(buttons & table): Fix some styles and remove hover menu by default from tables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.html
  projects/egeo/src/lib/st-table/README.md
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.ts
  projects/egeo/src/theme/components/_button.scss
  projects/egeo/src/theme/components/_table.scss
Labels: bug, style

#848 [NA] fix(table): Fix event "selectedAll"
  projects/egeo/src/lib/st-table/st-table.component.html
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
Labels: bug

#846 [GS-1808] feat(st-two-list): allows to show and control movement of disabled items in origin list
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-two-list-selection-demo/st-two-list-selection-demo.html
  projects/egeo-demo/src/app/demos/st-two-list-selection-demo/st-two-list-selection-demo.ts
  projects/egeo/src/lib/st-two-list-selection/list-item/list-item.component.spec.ts
  projects/egeo/src/lib/st-two-list-selection/list-item/list-item.component.ts
  projects/egeo/src/lib/st-two-list-selection/list-scroll/list-scroll.component.html
  projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.model.ts
  projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.spec.ts
  projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.ts
  projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.view.component.html
  projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.view.component.spec.ts
  projects/egeo/src/lib/st-two-list-selection/st-two-list-selection.view.component.ts
Labels: feature

#851 [NA] fix(st-dropdown): Fix wrong visualization of select dropdown
  CHANGELOG.md
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  projects/egeo/src/theme/components/_dropdown-menu.scss
  projects/egeo/src/theme/components/_select.scss
Labels: bug

#830 [NA]feat(header): Implement header UX new specs
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-filter-selector-demo/st-filter-selector-demo.component.html
  projects/egeo-demo/src/app/shared/header/header.component.scss
  projects/egeo/package.json
  projects/egeo/src/lib/st-header/README.md
  projects/egeo/src/lib/st-header/menu-option/menu-option.html
  projects/egeo/src/lib/st-header/menu-option/menu-option.scss
  projects/egeo/src/lib/st-header/menu-option/menu-option.ts
  projects/egeo/src/lib/st-header/st-header.component.spec.ts
  projects/egeo/src/lib/st-header/st-header.component.ts
  projects/egeo/src/lib/st-header/st-header.model.ts
  projects/egeo/src/theme/components/_header.scss
Labels: blocked, feature

#849 [NA] feat(modals): apply new UX styles
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
  projects/egeo/src/lib/st-modal/st-modal-buttons/st-modal-buttons.spec.ts
  projects/egeo/src/lib/st-modal/st-modal-buttons/st-modal-buttons.ts
  projects/egeo/src/lib/st-modal/st-modal.component.html
  projects/egeo/src/lib/st-modal/st-modal.component.scss
  projects/egeo/src/lib/st-modal/st-modal.component.ts
  projects/egeo/src/lib/st-modal/st-modal.model.ts
  projects/egeo/src/lib/st-modal/st-modal.service.spec.ts
  projects/egeo/src/lib/st-modal/st-modal.service.ts
  projects/egeo/src/theme/components/_modal.scss
Labels: style

#858 [NA] feat(modals): apply new UX styles
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
  projects/egeo/src/lib/st-modal/st-modal-buttons/st-modal-buttons.spec.ts
  projects/egeo/src/lib/st-modal/st-modal-buttons/st-modal-buttons.ts
  projects/egeo/src/lib/st-modal/st-modal.component.html
  projects/egeo/src/lib/st-modal/st-modal.component.scss
  projects/egeo/src/lib/st-modal/st-modal.component.ts
  projects/egeo/src/lib/st-modal/st-modal.model.ts
  projects/egeo/src/lib/st-modal/st-modal.service.spec.ts
  projects/egeo/src/lib/st-modal/st-modal.service.ts
  projects/egeo/src/theme/components/_modal.scss
Labels: cherry-pick, style

#857 [NA] style(st-foreground-notifications): new ux style
  CHANGELOG.md
  projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.scss
Labels: cherry-pick, style

#855 [NA]fix(theme): Fix tool buttons height
  projects/egeo/src/theme/components/_button.scss
Labels: bug, style

#856 [NA]fix(theme): Fix tool buttons height
  projects/egeo/src/theme/components/_button.scss
Labels: bug, cherry-pick, style

#852 [NA] style(st-foreground-notifications): new ux style
  CHANGELOG.md
  projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.scss
Labels: style

#853 [NA] fix(st-dropdown): Fix wrong visualization of select dropdown
  CHANGELOG.md
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  projects/egeo/src/theme/components/_dropdown-menu.scss
  projects/egeo/src/theme/components/_select.scss
Labels: bug, cherry-pick

#854 [NA] fix(st-dropdown): Fix wrong visualization of select dropdown
  CHANGELOG.md
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  projects/egeo/src/theme/components/_dropdown-menu.scss
  projects/egeo/src/theme/components/_select.scss
Labels: bug, cherry-pick

#860 [NA] Fix/styles foreground notifications
  projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.html
  projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.scss
Labels: style

#859 [NA]feat(theme): Update icon font to 1.27
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo-demo/tsconfig.app.json
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: feature

#861 [NA] fix(st-foreground-notifications): cherry-pick fix styles (#860)
  projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.html
  projects/egeo/src/lib/st-foreground-notifications/st-foreground-notifications.scss
Labels: cherry-pick

#862 [NA]feat(demo): fix wrong path fonts
  CHANGELOG.md
  package.json
  projects/egeo-demo/src/styles.scss
Labels: bug
