Repository Stratio/egeo, pull requests merged in 2020-06, with the labels that each got.

#941 [NA] fix(st-select): Fix bug when select is used without being part of a form and selected is changed from outside
  CHANGELOG.md
  projects/egeo/src/lib/st-select/st-select.html
  projects/egeo/src/lib/st-select/st-select.ts
Labels: bug

#942 [NA]fix(st-select): Added st-select without form demo
  projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.scss
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.scss
  projects/egeo-demo/src/app/demos/st-tag-input-demo/st-tag-input-demo.component.scss
Labels: enhancement

#940 [NA]feat(st-form) small class for form, st-input, st-select, st-search
  CHANGELOG.md
  projects/egeo/src/theme/components/_form-list.scss
  projects/egeo/src/theme/components/_form.scss
  projects/egeo/src/theme/components/_input.scss
  projects/egeo/src/theme/components/_search.scss
  projects/egeo/src/theme/components/_select.scss
  projects/egeo/src/theme/utils/_forms.scss
Labels: feature, style

#943 Cherry pick: [NA] fix(st-select): Fix bug when select is used without being part of a form and selected is changed from outside
  CHANGELOG.md
  projects/egeo/src/lib/st-select/st-select.html
  projects/egeo/src/lib/st-select/st-select.ts
Labels: bug, cherry-pick

#944 [NA]fix(st-select): St-select no form demo
  projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.scss
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.scss
  projects/egeo-demo/src/app/demos/st-tag-input-demo/st-tag-input-demo.component.scss
Labels: cherry-pick, demo

#945 [NA] feat(st-dynamic-table): Allow to hide a field through the UI definitions
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.spec.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: feature

#946 [NA] feat(st-table): Allow to display hover menu as "sticky" in order to be always visible
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.scss
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-table/README.md
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.ts
  projects/egeo/src/theme/components/_dynamic-table.scss
  projects/egeo/src/theme/components/_table.scss
Labels: feature

#947 [NA] fix(st-table): Fix wrong css variable name
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/theme/components/_table.scss
Labels: bug

#948 [NA] feat(st-table): Close filter menu when user clicks outside
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/lib/st-table/st-table.component.html
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.ts
  projects/egeo/src/lib/st-table/st-table.module.ts
  projects/egeo/src/theme/components/_table.scss
Labels: feature

#950 [NA] fix(st-table): Revert header changes when table does not have sticky hover menu
  projects/egeo/src/theme/components/_table.scss
Labels: style

#949 [NA] fix(st-pagination): Remove duplicated event emitted when items per page are changed
  CHANGELOG.md
  projects/egeo/src/lib/st-pagination/st-pagination.component.spec.ts
  projects/egeo/src/lib/st-pagination/st-pagination.component.ts
Labels: enhancement

#953 [NA]fix(st-select): fix when st-select recieve initial value from rea…
  CHANGELOG.md
  projects/egeo/src/lib/st-select/st-select.ts
Labels: bug

#951 [NA]fix(st-select): fix when st-select recieve initial value from reactive form
  CHANGELOG.md
  projects/egeo/src/lib/st-select/st-select.ts
Labels: bug, cherry-pick

#952 [NA]feat(dynamicTable): manage default ordering in table component
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: feature

#954 [NA] feat(st-table):st-table: Filter menus are displayed aligned to the left side of their cell
  CHANGELOG.md
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.spec.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
  projects/egeo/src/theme/components/_table.scss
Labels: enhancement

#955 [NA] fix(st-table): Simplify filter menu position calculation and added needed css variable
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.scss
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.spec.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
  projects/egeo/src/theme/components/_table.scss
Labels: enhancement

#956 [NA] feat(st-checkbox): Allow to customize the checked icon styles from outside using css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.html
  projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.scss
  projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.component.ts
  projects/egeo-demo/src/app/demos/st-checkbox-demo/st-checkbox-demo.module.ts
  projects/egeo/src/lib/st-checkbox/st-checkbox.component.html
  projects/egeo/src/theme/components/_checkbox.scss
Labels: feature, style

#957 [NA] feat(st-zero-page): Allow to customize some styles from outside using css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-zero-page-demo/st-zero-page-demo.component.html
  projects/egeo-demo/src/app/demos/st-zero-page-demo/st-zero-page-demo.component.ts
  projects/egeo-demo/src/app/demos/st-zero-page-demo/st-zero-page-demo.module.ts
  projects/egeo/src/theme/components/_zero-page.scss
Labels: feature, style

#958 [NA]style(st-form): cursor text on readonly fields
  projects/egeo/src/theme/components/_form.scss
Labels: enhancement

#959 [NA] feat(st-form): Allow to customize option labels using UI Definition object and render selects with integer value
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-form-demo/visual-field-improvements/st-visual-field-improvements-editor-demo.html
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
  projects/egeo/src/lib/st-form/README.md
  projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.interface.ts
  projects/egeo/src/lib/st-form/st-form.component.html
  projects/egeo/src/lib/st-form/st-form.component.ts
  projects/egeo/src/lib/st-form/st-form.model.ts
Labels: feature

#960 [NA]feat(egeo-theme): Add cursor text in readonly mode
  projects/egeo/src/theme/components/_form.scss
Labels: bug

#962 [NA] fix(st-dynamic-table): Fix bug in foreign key management when property does not exist on row
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: bug

#963 [NA] feat(st-bubble): Allow to customize the right margin of arrow and text font size
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/demos.routes.ts
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.html
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.scss
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.ts
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.module.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.module.ts
  projects/egeo/src/theme/components/_bubble.scss
Labels: enhancement, style

#964 [NA] feat(st-bubble): Allow to customize paddings and fix wrong css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-bubble-demo/st-bubble-demo.component.ts
  projects/egeo/src/theme/components/_bubble.scss
Labels: enhancement

#965 [NA] feat(st-dynamic-table): Remove management of the default sort
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-table/shared/order.ts
Labels: enhancement

#966 [NA] fix(st-table): Do not close filter menu when user clicks on its container and close it when enter key is pressed
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.scss
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.ts
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.module.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.module.ts
  projects/egeo-demo/src/styles.scss
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-table/README.md
  projects/egeo/src/lib/st-table/shared/st-popover-filter/README.md
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
  projects/egeo/src/lib/st-table/st-table.component.html
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.ts
Labels: bug, enhancement

#967 [NA]feat(sidebar): add custom icons and change styles according to UX
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.scss
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.ts
  projects/egeo/src/lib/st-sidebar/README.md
  projects/egeo/src/lib/st-sidebar/st-sidebar-item-list/README.md
  projects/egeo/src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.ts
  projects/egeo/src/lib/st-sidebar/st-sidebar.component.html
  projects/egeo/src/lib/st-sidebar/st-sidebar.component.ts
  projects/egeo/src/theme/components/_sidebar.scss
Labels: feature

#969 fix(modules): adding missing information
  projects/egeo-demo/src/app/demos/demos.routes.ts
  projects/egeo-demo/src/app/demos/st-header-demo/st-header-demo.routing.ts
  projects/egeo/src/lib/utils/demo-generator/demo-generator.routing.ts
Labels: chore

#970 [NA] fix(st-dropdown): Fix functionality to change the focused option with arrow keys and added css variables to customize styles
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.module.ts
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.scss
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
  projects/egeo/src/lib/st-select/st-select.html
  projects/egeo/src/lib/st-select/st-select.scss
  projects/egeo/src/theme/components/_select.scss
Labels: bug, demo, enhancement, style

#971 [SN-63] feat(st-form): Allow to hide a field without depending on another one
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.component.scss
  projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
  projects/egeo/src/lib/st-form/st-form.component.ts
  projects/egeo/src/lib/st-form/st-form.model.ts
Labels: feature

#972 [NA]fix(st-sidebar): add defaultActive to sidebar-item
  projects/egeo/src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.html
Labels: bug
