Repository Stratio/egeo, pull requests merged in 2020-04, with the labels that each got.

#879 [NA] feat(st-bubble-on-ellipsis): Allow to specify how many lines have to be displayed before ellipsis
  CHANGELOG.md
  package.json
  projects/egeo-demo/src/app/demos/st-bubble-on-ellipsis-demo/st-bubble-on-ellipsis-demo.component.html
  projects/egeo/karma.conf.js
  projects/egeo/src/lib/st-bubble-on-ellipsis/README.md
  projects/egeo/src/lib/st-bubble-on-ellipsis/st-bubble-on-ellipsis.component.scss
  projects/egeo/src/lib/st-bubble-on-ellipsis/st-bubble-on-ellipsis.component.spec.ts
  projects/egeo/src/lib/st-bubble-on-ellipsis/st-bubble-on-ellipsis.component.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  projects/egeo/src/lib/st-file-button/st-file-button.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  projects/egeo/src/lib/st-header/st-header.component.spec.ts
  projects/egeo/src/lib/st-header/st-header.component.ts
  projects/egeo/src/lib/st-modal/st-modal.component.spec.ts
  projects/egeo/src/lib/st-pagination/st-pagination.component.spec.ts
  projects/egeo/src/lib/st-pop/st-pop.component.spec.ts
  projects/egeo/src/lib/st-select/st-select.spec.ts
  projects/egeo/src/lib/st-tag-input/st-tag-input.component.spec.ts
  projects/egeo/src/lib/st-widget/st-widget.component.spec.ts
Labels: feature

#882 [NA] style(icon font): Update version to 1.32
  CHANGELOG.md
  assets/fonts/stratio-fonticon/ico_stratio.eot
  assets/fonts/stratio-fonticon/ico_stratio.svg
  assets/fonts/stratio-fonticon/ico_stratio.ttf
  assets/fonts/stratio-fonticon/ico_stratio.woff
  projects/egeo/src/theme/vendors/fonts/_stratio_fonticon.scss
Labels: style

#884 [NA] fix(st-dropdown-menu): Fix wrong visualization of the right aligned icon
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: bug, style

#883 [NA] feat(st-dropdown-menu): Emit events when mouse enters and leaves an item
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-filter-selector-demo/st-filter-selector-demo.component.ts
  projects/egeo/src/lib/st-dropdown-menu/README.md
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu-item/st-dropdown-menu-item.component.html
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
  projects/egeo/src/lib/st-filter-selector/README.md
  projects/egeo/src/lib/st-filter-selector/st-filter-selector.component.spec.ts
  projects/egeo/src/lib/st-filter-selector/st-filter-selector.component.ts
  projects/egeo/src/lib/st-filter-selector/st-filter-selector.template.html
Labels: feature

#885 [NA]fix(Egeo): Fix Angular 9 compatibility issues
  CHANGELOG.md
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/pipes/pipes.module.ts
  projects/egeo/src/lib/st-search/st-search.component.ts
  projects/egeo/src/lib/utils/event-window-manager.ts
Labels: enhancement

#886 [NA] feat(st-vertical-icon-tabs): Create component
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/barrels.ts
  projects/egeo-demo/src/app/demos/demos.routes.ts
  projects/egeo-demo/src/app/demos/public_api.ts
  projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.html
  projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.module.ts
  projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.scss
  projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.ts
  projects/egeo-demo/src/styles.scss
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-vertical-icon-tabs/README.md
  projects/egeo/src/lib/st-vertical-icon-tabs/st-icon-tabs.model.ts
  projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.html
  projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.scss
  projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.spec.ts
  projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.ts
  projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.module.ts
  projects/egeo/src/theme/components/_index.scss
  projects/egeo/src/theme/components/_vertical-icon-tabs.scss
  projects/egeo/src/theme/constants/_fonts.scss
Labels: feature

#887 [NA] fix(st-form-demo): Improve dynamic form demo and fix some bugs
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/json-schema.ts
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.component.scss
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.html
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.ts
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.component.scss
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.html
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.module.ts
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.ts
  projects/egeo-demo/src/app/demos/st-vertical-icon-tabs-demo/st-vertical-icon-tabs-demo.scss
  projects/egeo-demo/src/app/shared/title/title.component.scss
  projects/egeo-demo/src/styles.scss
  projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
  projects/egeo/src/lib/st-form/st-form.component.html
  projects/egeo/src/lib/st-form/st-form.component.ts
  projects/egeo/src/lib/st-vertical-icon-tabs/st-vertical-icon-tabs.component.scss
  projects/egeo/src/theme/components/_form.scss
Labels: demo

#889 [NA] chore(release): Change version to 20.1.0
  CHANGELOG.md
  pom.xml
Labels: release

#891 [NA] fix(st-table): Fix style to header filter icon
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo/src/theme/components/_table.scss
Labels: UX, bug, demo

#892 [NA] fix(st-header): Fix wrong visualization of user menu in small screen and change checking of option name sizes
  projects/egeo-demo/src/app/demos/st-header-demo/st-header-demo.component.html
  projects/egeo/src/lib/st-header/menu-option/menu-option.ts
  projects/egeo/src/lib/st-header/st-header.component.spec.ts
  projects/egeo/src/lib/st-header/st-header.component.ts
  projects/egeo/src/theme/components/_header.scss
Labels: bug, style

#893 [NA] fix(st-table): Filtered header fields are introduced as input and they are not modified inside table component
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/lib/st-table/README.md
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/theme/components/_table.scss
Labels: bug, style

#894 [NA] chore(colors): Added css variables to component theme in order to customize colors from outside
  CHANGELOG.md
  projects/egeo-demo/src/app/modules/theme/colors/colors.html
  projects/egeo-demo/src/app/modules/theme/colors/colors.scss
  projects/egeo/src/theme/components/_alerts.scss
  projects/egeo/src/theme/components/_breadcrumbs.scss
  projects/egeo/src/theme/components/_bubble.scss
  projects/egeo/src/theme/components/_button.scss
  projects/egeo/src/theme/components/_checkbox.scss
  projects/egeo/src/theme/components/_color-picker.scss
  projects/egeo/src/theme/components/_draggable-card.scss
  projects/egeo/src/theme/components/_dropdown-menu.scss
  projects/egeo/src/theme/components/_footer.scss
  projects/egeo/src/theme/components/_foreground-notifications.scss
  projects/egeo/src/theme/components/_form-base.scss
  projects/egeo/src/theme/components/_form-list.scss
  projects/egeo/src/theme/components/_form.scss
  projects/egeo/src/theme/components/_fullscreen-layout.scss
  projects/egeo/src/theme/components/_header.scss
  projects/egeo/src/theme/components/_horizontal-tabs.scss
  projects/egeo/src/theme/components/_info-box.scss
  projects/egeo/src/theme/components/_input.scss
  projects/egeo/src/theme/components/_items-list.scss
  projects/egeo/src/theme/components/_launcher.scss
  projects/egeo/src/theme/components/_modal.scss
  projects/egeo/src/theme/components/_page-title.scss
  projects/egeo/src/theme/components/_pagination.scss
  projects/egeo/src/theme/components/_pop-over.scss
  projects/egeo/src/theme/components/_radio-menu.scss
  projects/egeo/src/theme/components/_radio.scss
  projects/egeo/src/theme/components/_search.scss
  projects/egeo/src/theme/components/_select.scss
  projects/egeo/src/theme/components/_sidebar.scss
  projects/egeo/src/theme/components/_spinner.scss
  projects/egeo/src/theme/components/_switch.scss
  projects/egeo/src/theme/components/_table.scss
  projects/egeo/src/theme/components/_tag-input.scss
  projects/egeo/src/theme/components/_tag.scss
  projects/egeo/src/theme/components/_textarea.scss
  projects/egeo/src/theme/components/_toggle-buttons.scss
  projects/egeo/src/theme/components/_tooltip.scss
  projects/egeo/src/theme/components/_two-list.scss
  projects/egeo/src/theme/components/_vertical-icon-tabs.scss
  projects/egeo/src/theme/components/_vertical-tabs.scss
  projects/egeo/src/theme/components/_widget.scss
  projects/egeo/src/theme/components/_zero-page.scss
  projects/egeo/src/theme/constants/_colors.scss
  projects/egeo/src/theme/utils/_fonts.scss
  projects/egeo/src/theme/utils/_forms.scss
  projects/egeo/src/theme/utils/_other.scss
Labels: enhancement, style

#896 [NA]feat(egeo): Added egeo-ui-base as peerDependency
  package.json
  projects/egeo/package.json
Labels: enhancement
