Repository Stratio/egeo, pull requests merged in 2020-07, with the labels that each got.

#974 [NA] feat(st-sidebar): Display an optional message when search does not have any results and removed change event emitted after searching something
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.html
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.ts
  projects/egeo/src/lib/st-sidebar/README.md
  projects/egeo/src/lib/st-sidebar/st-sidebar.component.html
  projects/egeo/src/lib/st-sidebar/st-sidebar.component.spec.ts
  projects/egeo/src/lib/st-sidebar/st-sidebar.component.ts
  projects/egeo/src/theme/components/_sidebar.scss
Labels: bug, feature

#973 [NA] feat(st-dropdown-menu): Allow to customize some styles from outside using css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.html
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.module.ts
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: feature, style

#976 [NA] feat(st-dropdown-menu): Add css variable to border color when active
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: style

#977 [NA]feat(modal): Add customizable buttons and icons to basic modals
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.scss
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.module.ts
  projects/egeo/src/lib/st-modal/st-modal.component.html
  projects/egeo/src/lib/st-modal/st-modal.component.scss
  projects/egeo/src/lib/st-modal/st-modal.component.spec.ts
  projects/egeo/src/lib/st-modal/st-modal.service.spec.ts
  projects/egeo/src/lib/st-modal/st-modal.service.ts
  projects/egeo/src/theme/components/_modal.scss
Labels: feature

#978 [NA] feat(st-search): Allow to customize icon styles from outside using css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.html
  projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.module.ts
  projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.ts
  projects/egeo/src/lib/st-search/st-search.component.html
  projects/egeo/src/lib/st-search/st-search.component.scss
  projects/egeo/src/lib/st-search/st-search.component.spec.ts
  projects/egeo/src/theme/components/_search.scss
Labels: feature, style

#979 [NA] fix(st-search): Fix wrong css variables
  projects/egeo-demo/src/app/demos/st-search-demo/st-search-demo.ts
  projects/egeo/src/theme/components/_search.scss
Labels: bug

#980 [CDF-516] fix(st-header): margin between shortcut buttons
  CHANGELOG.md
  projects/egeo/src/theme/components/_header.scss
Labels: bug, style

#975 [NA] feat(st-modal): adds fadein fadeout animation
  CHANGELOG.md
  projects/egeo-demo/src/app/app.module.ts
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
  projects/egeo-demo/src/app/demos/st-modal2-demo/st-modal2-demo.component.html
  projects/egeo-demo/src/app/demos/st-modal2-demo/st-modal2-demo.component.ts
  projects/egeo/src/lib/st-modal/st-modal.component.html
  projects/egeo/src/lib/st-modal/st-modal.component.spec.ts
  projects/egeo/src/lib/st-modal/st-modal.component.ts
  projects/egeo/src/lib/st-modal/st-modal.service.spec.ts
  projects/egeo/src/lib/st-modal/st-modal.service.ts
  projects/egeo/src/lib/st-modal2/st-modal2.component.html
  projects/egeo/src/lib/st-modal2/st-modal2.component.spec.ts
  projects/egeo/src/lib/st-modal2/st-modal2.component.ts
Labels: enhancement

#981 [NA] fix(st-modal): fix disabled animation in modal
  projects/egeo/src/lib/st-modal/st-modal.component.ts
  projects/egeo/src/lib/st-modal/st-modal.service.ts
Labels: bug

#982 [NA] feat(modals): disable animation by default
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
  projects/egeo-demo/src/app/demos/st-modal2-demo/st-modal2-demo.component.html
  projects/egeo/src/lib/st-modal/st-modal.component.ts
  projects/egeo/src/lib/st-modal/st-modal.service.ts
  projects/egeo/src/lib/st-modal2/st-modal2.component.ts
Labels: enhancement

#983 [NA] fix(st-dropdown-menu): Revert active border to deprecated color
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.ts
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: bug, style

#984 [NA] fix(st-radio-group): active descendants to always find st-radio child
  CHANGELOG.md
  projects/egeo/src/lib/st-radio/st-radio.component.ts
Labels: bug

#985 [NA]feat(modal): add custom css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.ts
  projects/egeo/src/lib/st-modal/st-modal.component.scss
  projects/egeo/src/theme/components/_modal.scss
Labels: feature

#987 [NA] feat(st-dynamic-table): Allow to visualize date with a specific format and unify click cell events
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.ts
  projects/egeo-demo/src/app/demos/st-modal-demo/_form-base.scss
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.scss
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
  projects/egeo/src/theme/components/_dynamic-table.scss
Labels: breaking-change, feature

#988 [NA] feat(st-dynamic-table): Catch error when it tries to format an invalid date
  projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: enhancement

#993 [NA]revert(st-item-list-item): Revert remove st-item-list-item
  CHANGELOG.md
  projects/egeo/src/lib/barrels.ts
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.html
  projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.scss
  projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.spec.ts
  projects/egeo/src/lib/st-item-list/item-list-item/item-list-item.component.ts
  projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.html
  projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.scss
  projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.spec.ts
  projects/egeo/src/lib/st-item-list/item-list-scroll/item-list-scroll.component.ts
  projects/egeo/src/lib/st-item-list/st-item-list.component.html
  projects/egeo/src/lib/st-item-list/st-item-list.component.scss
  projects/egeo/src/lib/st-item-list/st-item-list.component.spec.ts
  projects/egeo/src/lib/st-item-list/st-item-list.component.ts
  projects/egeo/src/lib/st-item-list/st-item-list.model.ts
  projects/egeo/src/lib/st-item-list/st-item-list.module.ts
Labels: Revert

#994 [FC-99] fix(st-sidebar): Reset expanded list when items are changed
  CHANGELOG.md
  projects/egeo/src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.spec.ts
  projects/egeo/src/lib/st-sidebar/st-sidebar-item-list/st-sidebar-item-list.component.ts
Labels: bug

#995 [NA] fix(st-dynamic-table): Change input 'statusFilter' to 'activeFilterFields' to store the field keys with active filters
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.ts
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
Labels: breaking-change, enhancement

#997 [NA] fix(st-table): Wait for filter template loading in order to add submit button listener
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/directives/st-template-filter-submit.directive.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.module.ts
  projects/egeo/src/lib/st-table/st-table.module.ts
Labels: bug

#998 [FC-97] feat(st-button): Apply new design according to UX specifications
  CHANGELOG.md
  pom.xml
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.html
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.scss
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.ts
  projects/egeo/src/theme/components/_button.scss
Labels: UX, feature, style

#999 [FC-27] fix(st-modal): Fix wrong visualization of large titles
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.html
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.scss
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.html
  projects/egeo-demo/src/app/demos/st-modal-demo/st-modal-demo.component.scss
  projects/egeo/src/theme/components/_modal.scss
Labels: bug

#1001 [NA] feat(form demo): Use monaco editor to edit form json schema
  angular.json
  package.json
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.component.scss
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.html
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.module.ts
Labels: demo, enhancement
