Repository Stratio/egeo, pull requests merged in 2020-01, with the labels that each got.

#832 [NA]fix(bubble): remove min-width in bubble component
  CHANGELOG.md
  package.json
  projects/egeo/src/theme/components/_bubble.scss
Labels: bug

#833 [NA] style(st-dropdown-menu): Allow to display dropdown items in several lines when container's width is smaller
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dropdown-menu-demo/st-dropdown-menu-demo.html
  projects/egeo-demo/src/app/modules/demos/demo-layout/demo.layout.scss~HEAD
  projects/egeo/src/theme/components/_dropdown-menu.scss
  projects/egeo/src/theme/components/_input.scss
Labels: style

#834 [NA]feat(st-search): Add new Output event when select a filter
  CHANGELOG.md
  projects/egeo/src/lib/st-search/st-search.component.html
  projects/egeo/src/lib/st-search/st-search.component.ts
Labels: feature

#835 [CDF-512] feat(st-select): Renamed input 'search' to 'enabledSearcher' and change all internal search logic by event emitted to outside
  CHANGELOG.md
  pom.xml
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.html
  projects/egeo-demo/src/app/demos/st-select-demo/select-demo.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.spec.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.interface.ts
  projects/egeo/src/lib/st-select/st-select.html
  projects/egeo/src/lib/st-select/st-select.spec.ts
  projects/egeo/src/lib/st-select/st-select.ts
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: breaking-change, enhancement, feature

#836 [NA] fix(st-select): Fix bug in scroll listener. Sometimes when user does scroll it wasn't called
  CHANGELOG.md
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.html
  projects/egeo/src/lib/st-dropdown-menu/st-dropdown-menu.component.ts
Labels: bug

#838 Cherry pick: [NA] fix(st-dropdown-menu): Do not diplay dropdown items in several lines with menu list visualization
  CHANGELOG.md
  projects/egeo/src/theme/components/_dropdown-menu.scss
Labels: bug, cherry-pick, style

#842 [DGPB-3196] feat(st-table): Apply new UX specifications and remove custom theme 'white'
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/lib/st-table/README.md
  projects/egeo/src/lib/st-table/shared/st-table-cell/st-table-cell.component.scss
  projects/egeo/src/lib/st-table/shared/st-table-row/st-table-row.component.scss
  projects/egeo/src/lib/st-table/st-table.component.html
  projects/egeo/src/lib/st-table/st-table.component.scss
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.ts
  projects/egeo/src/theme/components/_table.scss
Labels: style
