Repository Stratio/egeo, pull requests merged in 2020-05, with the labels that each got.

#900 [NA] feat(st-spinner): Allow to customize its color from outside using css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-spinner-demo/st-spinner-demo.component.scss
  projects/egeo-demo/src/app/demos/st-spinner-demo/st-spinner-demo.html
  projects/egeo-demo/src/app/demos/st-spinner-demo/st-spinner-demo.module.ts
  projects/egeo-demo/src/app/demos/st-spinner-demo/st-spinner-demo.ts
  projects/egeo/src/lib/st-menu/st-menu-options/st-menu-options.component.scss
  projects/egeo/src/lib/st-progress-bar/st-progress-bar.scss
  projects/egeo/src/theme/components/_items-list.scss
  projects/egeo/src/theme/components/_launcher.scss
  projects/egeo/src/theme/components/_page-title.scss
  projects/egeo/src/theme/components/_sidebar.scss
  projects/egeo/src/theme/components/_spinner.scss
Labels: feature, style

#901 [NA] feat(st-sidebar): Allow to customize some styles from outside using css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.html
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.ts
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.module.ts
  projects/egeo/src/theme/components/_sidebar.scss
Labels: feature, style

#903 [NA] fix(st-table): Fix error in header style
  projects/egeo/src/theme/components/_table.scss
Labels: bug, style

#904 [NA]fix(egeo): Added type dependency in final package.json
  projects/egeo/ng-package.json
  projects/egeo/package.json
Labels: bug

#906 [NA]build(egeo): Upgrade to Gulp 4
  CHANGELOG.md
  package.json
  tools/gulp/gulpfile.ts
  tools/gulp/package-tools/index.ts
  tools/gulp/package-tools/sequence-task.ts
  tools/gulp/tasks/build.ts
  tools/gulp/tasks/egeo-publish.ts
  tools/gulp/tasks/generate-theme.ts
  tools/gulp/tasks/logo.ts
  tools/gulp/tasks/others.ts
  tools/gulp/util/task_helpers.ts
Labels: feature

#907 [NA] fix(st-dynamic-table, st-vertical-icon-tabs): Add dynamic table and vertical icon tabs component to barrels file
  projects/egeo/src/lib/barrels.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
  projects/egeo/src/theme/components/_table.scss
Labels: bug

#908 [NA] fix(st-tag): Fix default style without size class
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-tag-demo/st-tag-demo.component.html
  projects/egeo/src/theme/components/_tag.scss
Labels: bug, style

#910 [NA] fix(st-table): Revert removed functionality to row initialization in order to remove hover cell when it does not have any content
  projects/egeo/src/lib/st-table/shared/st-table-row/st-table-row.component.spec.ts
  projects/egeo/src/lib/st-table/shared/st-table-row/st-table-row.component.ts
Labels: bug

#911 [NA] fix(st-header): Fix style to icon buttons
  projects/egeo-demo/src/app/demos/st-header-demo/st-header-demo.component.html
  projects/egeo-demo/src/app/demos/st-header-demo/st-header-demo.component.ts
  projects/egeo/src/theme/components/_dropdown-menu.scss
  projects/egeo/src/theme/components/_header.scss
  projects/egeo/src/theme/components/_sidebar.scss
Labels: bug, style

#912 [NA] fix(st-sidebar): Only display in uppercase the first letter of title and items
  projects/egeo/src/theme/components/_sidebar.scss
Labels: style

#913 [NA]feat(table): Add event when filter icon is clicked
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
  projects/egeo/src/lib/st-table/shared/table-header.interface.ts
  projects/egeo/src/lib/st-table/st-table.component.html
  projects/egeo/src/lib/st-table/st-table.component.ts
Labels: feature

#915 [NA]fix(table): Fix table filters popup position
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.scss
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-table/st-table.component.scss
Labels: bug

#916 [FC-24]feat(st-table): Add sticky header to st-table
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.scss
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.scss
  projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.scss
  projects/egeo/src/lib/st-table/st-table.component.spec.ts
  projects/egeo/src/lib/st-table/st-table.component.ts
  projects/egeo/src/theme/components/_dynamic-table.scss
  projects/egeo/src/theme/components/_table.scss
Labels: enhancement

#914 [NA] feat(st-table): Allow to customize sort and filter icons using an input
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-dynamic-table/README.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.scss
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
  projects/egeo/src/lib/st-table/README.md
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.ts
  projects/egeo/src/lib/st-table/st-table.component.html
  projects/egeo/src/lib/st-table/st-table.component.ts
  projects/egeo/src/lib/st-table/st-table.interface.ts
  projects/egeo/src/theme/components/_table.scss
Labels: feature

#917 [NA] feat(st-pagination): Allow to customize icon classes of previous and next page buttons using input "iconClasses"
  CHANGELOG.md
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-pagination/README.md
  projects/egeo/src/lib/st-pagination/st-pagination.component.html
  projects/egeo/src/lib/st-pagination/st-pagination.component.ts
  projects/egeo/src/lib/st-pagination/st-pagination.interface.ts
Labels: feature

#918 [NA] feat(st-pop-over): Allow to choose menu placement and added input 'openToLeft' to be displayed from the button left side
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-pagination-demo/st-pagination-demo.component.html
  projects/egeo-demo/src/app/demos/st-pagination-demo/st-pagination-demo.component.ts
  projects/egeo-demo/src/app/demos/st-pagination-demo/st-pagination-demo.module.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/lib/st-pop-over/README.md
  projects/egeo/src/lib/st-pop-over/st-pop-over.component.html
  projects/egeo/src/lib/st-pop-over/st-pop-over.component.spec.ts
  projects/egeo/src/lib/st-pop-over/st-pop-over.component.ts
  projects/egeo/src/lib/st-table/shared/st-popover-filter/st-popover-filter.component.html
  projects/egeo/src/theme/components/_pagination.scss
  projects/egeo/src/theme/components/_pop-over.scss
Labels: enhancement

#919 [NA] feat(st-button): Allow to customize its style from outside using css variables
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.html
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.ts
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.module.ts
  projects/egeo/src/theme/components/_breadcrumbs.scss
  projects/egeo/src/theme/components/_button.scss
  projects/egeo/src/theme/components/_color-picker.scss
  projects/egeo/src/theme/components/_form.scss
  projects/egeo/src/theme/components/_header.scss
  projects/egeo/src/theme/components/_horizontal-tabs.scss
  projects/egeo/src/theme/components/_info-box.scss
  projects/egeo/src/theme/components/_modal.scss
Labels: enhancement, style

#920 [NA] fix(st-dynamic-table): Remove templateRef property from json schema and moved to ui definition object
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: enhancement

#921 [NA] feat(st-dynamic-table): Emit event when user leaves a row in order to hide hover menu
  projects/egeo/src/lib/st-dynamic-table/spec/st-dynamic-table.component.spec.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.spec.ts
Labels: enhancement

#922 [NA] style(st-button, st-table, st-form): Add some css variables to customize more styles from outside
  projects/egeo-demo/src/app/demos/st-button-demo/st-button-demo.component.ts
  projects/egeo-demo/src/app/demos/st-table-demo/st-table-demo.component.ts
  projects/egeo/src/theme/components/_button.scss
  projects/egeo/src/theme/components/_form-base.scss
  projects/egeo/src/theme/components/_table.scss
Labels: style

#923 [NA]feat(dynamicTable): Add Fk's and groups to dynamic table
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.html
  projects/egeo-demo/src/app/demos/st-dynamic-table-demo/st-dynamic-table-demo.component.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.html
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.scss
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: feature

#924 [NA]fix(dynamicTable): fix set of fields and export fk types
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: bug

#925 [NA] fix(st-dynamic-table): Fix emitted fk value and form field interface
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts
Labels: bug

#926 [NA]feat(egeo-theme): Update button colors
  CHANGELOG.md
  projects/egeo/src/theme/components/_button.scss
  projects/egeo/src/theme/constants/_colors.scss
Labels: enhancement

#927 [NA] feat(st-form): Allow to customize some styles using css variables and fix bug in pagination component
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.html
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.ts
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.html
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.module.ts
  projects/egeo-demo/src/app/demos/st-form-demo/st-form-demo.ts
  projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.component.scss
  projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.html
  projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.ts
  projects/egeo-demo/src/app/demos/st-sidebar-demo/st-sidebar-demo.component.ts
  projects/egeo/src/lib/st-form/README.md
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts
  projects/egeo/src/lib/st-form/st-form.component.html
  projects/egeo/src/lib/st-form/st-form.component.scss
  projects/egeo/src/lib/st-form/st-form.component.ts
  projects/egeo/src/lib/st-pagination/st-pagination.component.ts
  projects/egeo/src/theme/components/_form.scss
  projects/egeo/src/theme/components/_sidebar.scss
  projects/egeo/src/theme/constants/_colors.scss
  projects/egeo/src/theme/utils/_forms.scss
Labels: bug, feature

#928 [NA]feat(st-fullscreen-layout): Add close button to fullscreen
  CHANGELOG.md
  projects/egeo/src/lib/st-fullscreen-layout/README.md
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.html
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.scss
  projects/egeo/src/lib/st-fullscreen-layout/st-fullscreen-layout.ts
  projects/egeo/src/theme/components/_fullscreen-layout.scss
Labels: enhancement

#929 [NA] feat(st-form): Define interfaces and allow to display a link before field using property 'link' in ui block
  CHANGELOG.md
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.html
  projects/egeo-demo/src/app/demos/st-form-demo/form-editor/st-form-editor-demo.ts
  projects/egeo-demo/src/app/demos/st-form-demo/visual-customization/st-theme-customization-demo.ts
  projects/egeo/src/lib/index.ts
  projects/egeo/src/lib/st-form/README.md
  projects/egeo/src/lib/st-form/spec/resources/json-schema.ts
  projects/egeo/src/lib/st-form/spec/st-form.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.html
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.spec.ts
  projects/egeo/src/lib/st-form/st-form-field/st-form-field.component.ts
  projects/egeo/src/lib/st-form/st-form.component.html
  projects/egeo/src/lib/st-form/st-form.component.ts
  projects/egeo/src/lib/st-form/st-form.model.ts
  projects/egeo/src/theme/components/_form.scss
  projects/egeo/src/theme/components/_table.scss
Labels: enhancement, feature

#930 [NA]feat(dynamicTable): Add types to fields
  CHANGELOG.md
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.model.ts
  projects/egeo/src/lib/st-dynamic-table/utils/st-dynamic-table.utils.ts
Labels: feature

#931 [NA] fix(st-modal): Fix title weight
  projects/egeo/src/theme/components/_modal.scss
Labels: style

#932 [NA] fix(st-dynamic-table): Update header fields when json schema or ui definitions are updated
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
Labels: bug

#933 [NA] fix(st-dynamic-table): Update header fields when json schema or ui definitions are updated
  projects/egeo/src/lib/st-dynamic-table/st-dynamic-table.component.ts
Labels: bug, cherry-pick

#937 [NA]fix(egeo): Moved json-schema dependency from devDependeny to dependency in final json
  projects/egeo/package.json
Labels: bug, cherry-pick

#939 [NA]fix(egeo): Moved json-schema dependency from devDependeny to dependency in final json
  projects/egeo/package.json
Labels: bug
